# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cholBatchBackend <- function(A, D, Nglobal, Nlocal, NlocalCache) {
    invisible(.Call('_gpuRandom_cholBatchBackend', PACKAGE = 'gpuRandom', A, D, Nglobal, Nlocal, NlocalCache))
}

cpp_gpuFisher_test <- function(srR, scR, resultsR, streamsR, max_global_size, max_local_size) {
    .Call('_gpuRandom_cpp_gpuFisher_test', PACKAGE = 'gpuRandom', srR, scR, resultsR, streamsR, max_global_size, max_local_size)
}

cpp_gpuRn <- function(xR, streamsR, max_global_size, max_local_size, random_type, precision_type) {
    .Call('_gpuRandom_cpp_gpuRn', PACKAGE = 'gpuRandom', xR, streamsR, max_global_size, max_local_size, random_type, precision_type)
}

cpp_mrg31k3pCreateStreams <- function(numWorkItems) {
    .Call('_gpuRandom_cpp_mrg31k3pCreateStreams', PACKAGE = 'gpuRandom', numWorkItems)
}

maternBatchBackend <- function(var, coords, param, Nglobal, Nlocal) {
    invisible(.Call('_gpuRandom_maternBatchBackend', PACKAGE = 'gpuRandom', var, coords, param, Nglobal, Nlocal))
}

multiplyLowerDiagonalBatchBackend <- function(C, A, D, B, diagIsOne, transformD, Nglobal, Nlocal, NlocalCache) {
    .Call('_gpuRandom_multiplyLowerDiagonalBatchBackend', PACKAGE = 'gpuRandom', C, A, D, B, diagIsOne, transformD, Nglobal, Nlocal, NlocalCache)
}

multiplyDiagonalBatchBackend <- function(C, A, B, Nglobal, Nlocal) {
    .Call('_gpuRandom_multiplyDiagonalBatchBackend', PACKAGE = 'gpuRandom', C, A, B, Nglobal, Nlocal)
}

#' Multiply lower triangular matrices
#' 
#' Multiplies a lower triangular matrix by a rectangular matrix
#'
#' @param C output matrices, stacked row-wise
#' @param A lower triangular matrices
#' @param B rectangular matrix or matrices
#' @param Nglobal vector of number of global work items
#' @param Nlocal vector of number of local work items
#' @param NlocalCache elements in local cache
#' @export
multiplyLowerBatchBackend <- function(C, A, B, diagIsOne, Nglobal, Nlocal, NlocalCache) {
    .Call('_gpuRandom_multiplyLowerBatchBackend', PACKAGE = 'gpuRandom', C, A, B, diagIsOne, Nglobal, Nlocal, NlocalCache)
}

