# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

backsolveBatchBackend <- function(C, A, B, Cstartend, Astartend, Bstartend, numbatchB, diagIsOne, Nglobal, Nlocal, NlocalCache) {
    .Call('_gpuRandom_backsolveBatchBackend', PACKAGE = 'gpuRandom', C, A, B, Cstartend, Astartend, Bstartend, numbatchB, diagIsOne, Nglobal, Nlocal, NlocalCache)
}

backsolveBatchBackend2 <- function(C, A, B, diagIsOne, Nglobal, Nlocal, NlocalCache) {
    .Call('_gpuRandom_backsolveBatchBackend2', PACKAGE = 'gpuRandom', C, A, B, diagIsOne, Nglobal, Nlocal, NlocalCache)
}

cholBatchBackend <- function(A, D, Astartend, Dstartend, numbatchD, Nglobal, Nlocal, NlocalCache) {
    invisible(.Call('_gpuRandom_cholBatchBackend', PACKAGE = 'gpuRandom', A, D, Astartend, Dstartend, numbatchD, Nglobal, Nlocal, NlocalCache))
}

#' Multiply crossproduct matrices
#' 
#' Computes C = t(A) D A
#'
#' @param C output matrices, stacked row-wise
#' @param A rectangular matrices
#' @param D rectangular matrix, columns are diagonals
#' @param invertD set to 1 for C = t(A) D^(-1) A
#' @param Nglobal vector of number of global work items
#' @param Nlocal vector of number of local work items
#' @param NlocalCache elements in local cache
#' @export
crossprodBatchBackend <- function(C, A, D, invertD, Cstartend, Astartend, Dstartend, Nglobal, Nlocal, NlocalCache) {
    .Call('_gpuRandom_crossprodBatchBackend', PACKAGE = 'gpuRandom', C, A, D, invertD, Cstartend, Astartend, Dstartend, Nglobal, Nlocal, NlocalCache)
}

gemmBatchBackend <- function(A, B, C, Arowbatch, Browbatch, Acolbatch, Bcolbatch, need_transpose, Nglobal) {
    .Call('_gpuRandom_gemmBatchBackend', PACKAGE = 'gpuRandom', A, B, C, Arowbatch, Browbatch, Acolbatch, Bcolbatch, need_transpose, Nglobal)
}

#' 
#' Multiplies a rectangular matrix by a rectangular matrix in batches
#'
#' @param C output matrices, stacked row-wise
#' @param A rectangular matrices
#' @param B rectangular matrices 
#' @param Nglobal vector of number of global work items//' @param Nlocal vector of number of local work items//' @param NlocalCache elements in local cache
#' @export
gemmBatch2backend <- function(A, B, C, transposeABC, submatrixA, submatrixB, submatrixC, batches, workgroupSize, NlocalCache, verbose) {
    .Call('_gpuRandom_gemmBatch2backend', PACKAGE = 'gpuRandom', A, B, C, transposeABC, submatrixA, submatrixB, submatrixC, batches, workgroupSize, NlocalCache, verbose)
}

cpp_gpuFisher_test <- function(xR, resultsR, B, streamsR, max_global_size, max_local_size) {
    .Call('_gpuRandom_cpp_gpuFisher_test', PACKAGE = 'gpuRandom', xR, resultsR, B, streamsR, max_global_size, max_local_size)
}

cpp_mrg31k3pCreateStreams <- function(numWorkItems) {
    .Call('_gpuRandom_cpp_mrg31k3pCreateStreams', PACKAGE = 'gpuRandom', numWorkItems)
}

#' Random number generation
#' 
#' Fills a matrix with random numbers
#'
#' @param x output matrix
#' @param streams matrix of random number seeds
#' @param max_global_size vector of length 2, number of work items
#' @param random_type one of "uniform" or "normal"
#' 
#' @export
gpuRnBackend <- function(x, streams, max_global_size, random_type) {
    .Call('_gpuRandom_gpuRnBackend', PACKAGE = 'gpuRandom', x, streams, max_global_size, random_type)
}

cpp_gpu_qqnorm <- function(outR, mu, sigma, lowertail, max_global_size, max_local_size) {
    .Call('_gpuRandom_cpp_gpu_qqnorm', PACKAGE = 'gpuRandom', outR, mu, sigma, lowertail, max_global_size, max_local_size)
}

likfitGpu_Backend <- function(coordsGpuR, bigparamsBatchR, yXR, betasR, bigvariancesR, jacobianR, finalssqBetaR, finalssqXR, finalssqYR, finallogDR, finallogPR, finalbetahatR, finalLogLikR, n, p, groupsize, colbatch, form, workgroupSize, localSize, NlocalCache, verbose) {
    invisible(.Call('_gpuRandom_likfitGpu_Backend', PACKAGE = 'gpuRandom', coordsGpuR, bigparamsBatchR, yXR, betasR, bigvariancesR, jacobianR, finalssqBetaR, finalssqXR, finalssqYR, finallogDR, finallogPR, finalbetahatR, finalLogLikR, n, p, groupsize, colbatch, form, workgroupSize, localSize, NlocalCache, verbose))
}

likfitGpu_BackendP <- function(yx, coords, params, boxcox, betas, ssqY, ssqX, detVar, detReml, jacobian, NparamPerIter, workgroupSize, localSize, NlocalCache, verbose, ssqYX, LinvYX, QinvSsqYx) {
    invisible(.Call('_gpuRandom_likfitGpu_BackendP', PACKAGE = 'gpuRandom', yx, coords, params, boxcox, betas, ssqY, ssqX, detVar, detReml, jacobian, NparamPerIter, workgroupSize, localSize, NlocalCache, verbose, ssqYX, LinvYX, QinvSsqYx))
}

logfactsumBackend <- function(xR, numWorkItems) {
    .Call('_gpuRandom_logfactsumBackend', PACKAGE = 'gpuRandom', xR, numWorkItems)
}

rowsumBackend <- function(xR, SumR, type, log) {
    invisible(.Call('_gpuRandom_rowsumBackend', PACKAGE = 'gpuRandom', xR, SumR, type, log))
}

matrix_matrix_sumBackend <- function(aR, bR, sumR, numWorkItems) {
    invisible(.Call('_gpuRandom_matrix_matrix_sumBackend', PACKAGE = 'gpuRandom', aR, bR, sumR, numWorkItems))
}

matrix_scalar_sumBackend <- function(matrixR, valueR, sumR, numWorkItems) {
    invisible(.Call('_gpuRandom_matrix_scalar_sumBackend', PACKAGE = 'gpuRandom', matrixR, valueR, sumR, numWorkItems))
}

matrix_vector_sumBackend <- function(matrixR, vectorR, sumR, byrow, numWorkItems) {
    invisible(.Call('_gpuRandom_matrix_vector_sumBackend', PACKAGE = 'gpuRandom', matrixR, vectorR, sumR, byrow, numWorkItems))
}

fillParamsExtra <- function(param) {
    invisible(.Call('_gpuRandom_fillParamsExtra', PACKAGE = 'gpuRandom', param))
}

maternBatchBackend <- function(var, coords, param, Nglobal, Nlocal, startrow, numberofrows, verbose = 0L) {
    invisible(.Call('_gpuRandom_maternBatchBackend', PACKAGE = 'gpuRandom', var, coords, param, Nglobal, Nlocal, startrow, numberofrows, verbose))
}

multiplyLowerDiagonalBatchBackend <- function(C, A, D, B, diagIsOne, transformD, Nglobal, Nlocal, NlocalCache) {
    .Call('_gpuRandom_multiplyLowerDiagonalBatchBackend', PACKAGE = 'gpuRandom', C, A, D, B, diagIsOne, transformD, Nglobal, Nlocal, NlocalCache)
}

multiplyDiagonalBatchBackend <- function(C, A, B, inverse, Nglobal, Nlocal) {
    .Call('_gpuRandom_multiplyDiagonalBatchBackend', PACKAGE = 'gpuRandom', C, A, B, inverse, Nglobal, Nlocal)
}

#' Multiply lower triangular matrices
#' 
#' Multiplies a lower triangular matrix by a rectangular matrix
#'
#' @param C output matrices, stacked row-wise
#' @param A lower triangular matrices
#' @param B rectangular matrix or matrices
#' @param Nglobal vector of number of global work items
#' @param Nlocal vector of number of local work items
#' @param NlocalCache elements in local cache
#' @export
multiplyLowerBatchBackend <- function(C, A, B, diagIsOne, Nglobal, Nlocal, NlocalCache) {
    .Call('_gpuRandom_multiplyLowerBatchBackend', PACKAGE = 'gpuRandom', C, A, B, diagIsOne, Nglobal, Nlocal, NlocalCache)
}

