# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_gpuFisher_test <- function(srR, scR, resultsR, streamsR, max_global_size, max_local_size) {
    .Call('_gpuRandom_cpp_gpuFisher_test', PACKAGE = 'gpuRandom', srR, scR, resultsR, streamsR, max_global_size, max_local_size)
}

cpp_gpuRn <- function(xR, streamsR, max_global_size, max_local_size, random_type, precision_type) {
    .Call('_gpuRandom_cpp_gpuRn', PACKAGE = 'gpuRandom', xR, streamsR, max_global_size, max_local_size, random_type, precision_type)
}

cpp_mrg31k3pCreateStreams <- function(numWorkItems) {
    .Call('_gpuRandom_cpp_mrg31k3pCreateStreams', PACKAGE = 'gpuRandom', numWorkItems)
}

maternBatchBackend <- function(var, coords, param, Nglobal, Nlocal) {
    invisible(.Call('_gpuRandom_maternBatchBackend', PACKAGE = 'gpuRandom', var, coords, param, Nglobal, Nlocal))
}

