

```{r setup, include=FALSE}
fName = 'slides.Rmd'
Makefile = system.file('src','knitrMakefile', package='Pmisc')
toCompile = paste("make -f ", Makefile, ' ', gsub("Rmd$","pdf", fName), sep='')
toCompile

# packages
library('knitr')
library('Pmisc')

# hook for multicolumn plots
knitr::knit_hooks$set(plot=hook_plot_beamer) 

# hook for smaller plot margins
knitr::knit_hooks$set(
	marginsp = function(before, options, envir){	
		if(!before) return()
		par(mar=c(1.5+0.9*options$marginsp,
				1.5+0.9*options$marginsp,0.2,0.2),
				mgp=c(1.45, 0.45, 0),cex=1.25)
	}		
)

# hook for half width
knitr::opts_hooks$set(half = function(options) {
  options$tidy.opts = list(width.cutoff = options$tidy.opts$width.cutoff/2)
  options
})

# default chunk options
knitr::opts_chunk$set(echo=FALSE, prompt=TRUE, comment=NA,
		dev='pdf', marginsp=1, fig.start='#',
		fig.width=8, fig.height=4.5, half=NULL,
		tidy=TRUE,tidy.opts=list(indent=2, width.cutoff=55)
)

options(width=80)

# write a bibliography
knitr::write_bib(
	c('geostatsp', 'knitr'),
	file='myBib.bib'
)
```

```{r theHeader, echo=FALSE}
Pmisc::markdownHeader(
	title="Pmisc slides example", 		
	author='Patrick Brown',
 	bibliography='myBib.bib',
	theme='Singapore',
	beamer=TRUE,
	classoption=c(
  		aspectratio=169,
		xcolor='dvipsnames'),
	biblatexoptions = c(
		maxbibnames=20,
		maxcitenames=2,doi='false'),
	headerincludes =c(
  		'\\usecolortheme[named=MidnightBlue]{structure}',
  		'\\DeclareMathOperator{\\var}{var}',
		'\\DeclareMathOperator{\\E}{E}')
)
```

```{r theHeaderAgain, eval=FALSE, include=FALSE}
cat(
		Pmisc::markdownHeader(
				title="Pmisc slides example", 		
				author='Patrick Brown',
				bibliography='myBib.bib',
				theme='Singapore',
				beamer=TRUE,
				classoption=c(
						aspectratio=169,
						xcolor='dvipsnames'),
				biblatexoptions = c(
						maxbibnames=20,
						maxcitenames=2,doi='false'),
				headerincludes =c(
						'\\usecolortheme[named=MidnightBlue]{structure}',
						'\\DeclareMathOperator{\\var}{var}',
						'\\DeclareMathOperator{\\E}{E}')
		)
)
```


# Some references


- `@R-knitr`: @R-knitr
- `[@R-knitr]`: @R-knitr
- `[see @R-geostatsp for example]`: [see @R-geostatsp for example]
- `\fullcite{R-geostatsp}`: \fullcite{R-geostatsp}


# Markdown citations



```{r aplot, fig.height=3, fig.width=8, fig.ncol=2, fig.cap='A few plots', fig.subcap=c('a','b','c','d'), echo=FALSE, fig.start='#'}

plot(1:10)

plot(1:10+2)


plot(1:10-4)


plot(1:10+4)

```

# A few more plots


\bcolb{Code}

```{r twoplots, echo=TRUE, eval=FALSE, half=TRUE}
plot(rnorm(10), xlab='index', ylab='value', pch=1:10)

plot(runif(10), xlab='index', ylab='value', pch=1:10)
```

\newcolb{Output}

```{r twoplots, fig.height=3, fig.width=8, fig.subcap=c('normal','uniform'), echo=FALSE, fig.start=NULL}
```
        
\ecolb



