# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cholBatchBackend <- function(A, D, Nglobal, Nlocal, NlocalCache = 500L) {
    invisible(.Call('_geostatsgpu_cholBatchBackend', PACKAGE = 'geostatsgpu', A, D, Nglobal, Nlocal, NlocalCache))
}

cpp_cholGpu <- function(xR, DR, diagWorkingR, diagTimesRowOfAR, MCglobal, MClocal, localStorage, colGroupwise, Ncrossprod, verbose, kernelR) {
    .Call('_geostatsgpu_cpp_cholGpu', PACKAGE = 'geostatsgpu', xR, DR, diagWorkingR, diagTimesRowOfAR, MCglobal, MClocal, localStorage, colGroupwise, Ncrossprod, verbose, kernelR)
}

gpuNlocal <- function(kernel, functionName, ctx_id) {
    .Call('_geostatsgpu_gpuNlocal', PACKAGE = 'geostatsgpu', kernel, functionName, ctx_id)
}

maternBatchBackend <- function(var, coords, param, Nglobal, Nlocal) {
    invisible(.Call('_geostatsgpu_maternBatchBackend', PACKAGE = 'geostatsgpu', var, coords, param, Nglobal, Nlocal))
}

cpp_maternGpuD <- function(varR, coordsR, DofLDLR, param, form, numWorkItems, numLocalItems) {
    .Call('_geostatsgpu_cpp_maternGpuD', PACKAGE = 'geostatsgpu', varR, coordsR, DofLDLR, param, form, numWorkItems, numLocalItems)
}

cpp_maternGpuF <- function(varR, coordsR, DofLDLR, param, form, numWorkItems, numLocalItems) {
    .Call('_geostatsgpu_cpp_maternGpuF', PACKAGE = 'geostatsgpu', varR, coordsR, DofLDLR, param, form, numWorkItems, numLocalItems)
}

cpp_lu <- function(xR, dR) {
    .Call('_geostatsgpu_cpp_lu', PACKAGE = 'geostatsgpu', xR, dR)
}

