# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_cholGpu <- function(xR, DR, diagWorkingR, diagTimesRowOfAR, MCglobal, MClocal, localStorage, colGroupwise, Ncrossprod, verbose, kernelR) {
    .Call('_geostatsgpu_cpp_cholGpu', PACKAGE = 'geostatsgpu', xR, DR, diagWorkingR, diagTimesRowOfAR, MCglobal, MClocal, localStorage, colGroupwise, Ncrossprod, verbose, kernelR)
}

gpuNlocal <- function(kernel, functionName, ctx_id) {
    .Call('_geostatsgpu_gpuNlocal', PACKAGE = 'geostatsgpu', kernel, functionName, ctx_id)
}

cpp_maternGpu <- function(varR, DofLDLR, XYR, crossprodR, coordsR, paramR, type, upper, max_local_size, ctx_id) {
    .Call('_geostatsgpu_cpp_maternGpu', PACKAGE = 'geostatsgpu', varR, DofLDLR, XYR, crossprodR, coordsR, paramR, type, upper, max_local_size, ctx_id)
}

cpp_lu <- function(xR, ctx_id) {
    .Call('_geostatsgpu_cpp_lu', PACKAGE = 'geostatsgpu', xR, ctx_id)
}

