<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Mulitply Lower Triangular}
-->


# Multiply Lower Triangular Matrix

```{r date}
date()
```


```{r packages, results='hide'}
library('gpuR')
```



```{r memoryAvailable, echo=TRUE}
if(system("hostname", TRUE) == 'englishbreakfast') {
  setContext(2)
}
gpuInfo()$deviceName
gpuInfo()$maxAllocatableMem/(1024^2)
```

Set up spatial data

```{r setupData}
myraster = geostatsp::squareRaster(raster::extent(-3,3,-4,4), 30)
param = c(range=4, shape=1.5, anisoRatio=2, anisoAngleDegrees=25,variance=20)

lowerMat = as.matrix(geostatsp::matern(myraster, param=param, type='cholesky'))
lowerMatGpu = vclMatrix(lowerMat, type='double')

set.seed(0)
zMat = matrix(rnorm(nrow(lowerMat)*4), ncol=4)
zMatGpu = vclMatrix(zMat, type=typeof(lowerMatGpu))
```


```{r multiply}
xCpu = lowerMat %*% zMat

xGpu = vclMatrix(0, nrow(zMatGpu), ncol(zMatGpu), type=gpuR::typeof(zMatGpu))

gpuMatrix::multiplyLower(xGpu, lowerMatGpu, zMatGpu, 16, 2, 5, gpuR::typeof(xGpu))

xCpu[1:7,]
as.matrix(xGpu)[1:7,]
quantile(xCpu - as.matrix(xGpu))
```

```{r plot}
mybrick = raster::brick(myraster, nl= ncol(xGpu))
raster::values(mybrick) = as.vector(as.matrix(xGpu))
myBreaks = unique(round(
	seq(floor(min(raster::minValue(mybrick))), 
	max(ceiling(raster::maxValue(mybrick))), len=9)
	))
raster::plot(mybrick, breaks = myBreaks, col=terrain.colors(length(myBreaks)-1))
```

# extra info

```{r gpuInfo, echo=TRUE}
gpuR::gpuInfo()
```




