<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Sparse}
-->

```{r stuff}

library(Matrix)

xC = forceSymmetric(sparseMatrix(
	c(1,3,1,2,4,4,1,3,5,2,5,6),
	c(1,1,2,2,3,4,5,3,3,6,5,6),
	x = c(7.1, 8.2, 1.1, 2.2, 3.3, 3.3, 4.4, 5.5, 5.6,-2.1, 9.1, 1.1),
	dims = c(6,6)))

x <- as(xC, "RsparseMatrix")

gpuMatrix:::generate_row_block_information(x)
gpuMatrix:::generate_row_block_information(x, 2L)

library('gpuMatrix')
vclX = getVclSparseMatrix(x)

x
sparseMatrix(
  p = as.vector(vclX$row_jumper), 
  j = as.vector(vclX$col_buffer),
  x = as.vector(vclX$elements),
  index1=FALSE)

```

```{r chol}

cholX = Cholesky(x, perm=TRUE, LDL=TRUE)
vclCholX = getVclSparseMatrix(cholX)

xP = as(x[1+cholX@perm, 1+cholX@perm], "RsparseMatrix")
vclXp = getVclSparseMatrix(xP)






```


```{r multiMatrix}


xMulti = getVclSparseMultiMatrix(xP, 0:3)

xP
sparseMatrix(
  p = as.vector(xMulti$row_jumper), 
  j = as.vector(xMulti$col_buffer),
  x = as.vector(xMulti$elements[,3]),
  index1=FALSE)

xCholMulti = getVclSparseMultiMatrix(cholX, 3)
sparseMatrix(
  p = as.vector(xCholMulti$row_jumper), 
  i = as.vector(xCholMulti$col_buffer),
  x = as.vector(xCholMulti$elements[,3]),
  index1=FALSE)
sparseMatrix(
  p = as.vector(cholX@p), 
  i = as.vector(cholX@i),
  x = as.vector(cholX@x),
  index1=FALSE)
```

```{r s4}
'
compressed_matix<double> xGpu(
	xGpuList$rows, xGpuList$cols, 
	xGpuList$nonzeros,
	viennacl::traits::context(xGpuList$elements));

xGpu.handle1() = xGpuList$row_jumper.handle();
xGpu.handle2() = xGpuList$col_buffer.handle();
xGpu.handle() = xGpuList$elements.handle();
xGpu.generate_row_block_information();
'

setClass('vclSparseMatrix', 
         slots = c(
         	i="externalptr",
         	j="externalptr",
         	x="externalptr",
            .context_index = "integer",
            .platform_index = "integer",
            .platform = "character",
            .device_index = "integer",
            .device = "character"))

setClass("fvclSparseMatrix",
         contains = "vclSparseMatrix",
         validity = function(object) {
             if( gpuR::typeof(object) != "float"){
                 return("fvclSparseMatrix must be of type 'float'")
             }
             TRUE
         })








```