<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Fisher test}
-->

`https://github.com/clMathLibraries/clRNG`


## Fisher test simulation

```{r date}
date()
```


```{r packages, results='hide'}
library('gpuR')
```

```{r memoryAvailable, echo=TRUE}
setContext(   grep('OpenCL 2.1', listContexts()$platform)[1]    )
gpuInfo()$deviceName
gpuInfo()$maxAllocatableMem/(1024^3)
```

Example 1
```{r  teaTasting}
TeaTasting <-matrix(c(21,17,5,19,38,6,26,12,9),nrow=3)

TeaTasting
## Using the R function 
fisher.test(TeaTasting)
fisher.test(TeaTasting, alternative = "t",  simulate.p.value = TRUE, B = 1e5)
```


 


Example 2
```{r eval=TRUE}
x<- matrix(c(2, 10, 15, 3), nrow = 2)

fisher.test(x, alternative = "t",  simulate.p.value = TRUE, B = 1e5)

Nglobal = c(16,64)
streams = gpuRandom::CreateStreams(prod(Nglobal))


res1 = gpuRandom::fisher.sim(x, 10000L, returnStatistics=TRUE, 
                             type="double", streams, workgroupSize = Nglobal)

str(res1)
hist(as.vector(res1$sim))
```

```{r ex2, eval=TRUE}
res2 = gpuRandom::fisher.sim(x, 100000L, returnStatistics=FALSE, type="double", streams, workgroupSize = Nglobal)
str(res2)
```






























