<!--
%\VignetteEngine{knitr::docco_linear}
%\VignetteIndexEntry{Examples of map layers}
-->




# Examples of map layers



```{r setup,include=FALSE}

library('knitr')
library('mapmisc')


reRun=("reRun" %in% commandArgs(trailingOnly = TRUE))


if( Sys.info()['user'] =='patrick') {
	opts_chunk$set(dpi=72,dev.args=list(bg='white'))	
} else {	
	opts_chunk$set(dpi=36,dev.args=list(bg='white'))	
}

theNames = names(osmTiles())
africaExtent = c(25, 25)
trafalgarSquare=c(-0.128056,51.508056)
stjohns=c(-52.62, 47.53)

```


```{r downloadTiles,include=FALSE}
if(reRun) {
africaTiles = openmap(africaExtent, path=theNames,zoom=2,
    verbose=TRUE, 
    buffer=c(1,1))

londonTiles = openmap(trafalgarSquare,zoom=12,path=theNames,verbose=TRUE)

nfTiles = openmap(stjohns, zoom=14, path=theNames, verbose=TRUE)



# make sure all data is stored in memory not on disk
# so that caching will work
for(D in names(africaTiles))
	values(africaTiles[[D]]) = 	values(africaTiles[[D]])
for(D in names(londonTiles))
	values(londonTiles[[D]]) = 	values(londonTiles[[D]])
for(D in names(nfTiles))
	values(nfTiles[[D]]) = 	values(nfTiles[[D]])
if(file.exists("../inst/extdata"))
	save(africaTiles, londonTiles, nfTiles,
			file="../inst/extdata/tiles.RData",
			compress="xz")
} else { # don't rerun
	load(system.file("extdata", "tiles.RData", package = "mapmisc"))
}
```


The following are some examples of maps produced with `mymap=openmap(x, path="something")`


```{r someTiles, echo=FALSE, results='asis', fig.height=3, fig.width=3}


mytiles = list(africaTiles, londonTiles, nfTiles)

for(D in theNames){
	Dsub = gsub("-",".", D)

	threeTiles = length(
			grep(paste("^", Dsub, 
							"([rR]ed|[gG]reen|[bB]lue)$", 
							sep=""), 
			names(mytiles[[1]]))
		)>0 | 	length(
				grep(paste("^", Dsub, 
								"([rR]ed|[gG]reen|[bB]lue)$", 
								sep=""), 
						names(mytiles[[2]]))
		)>0

	
	cat("\n\n# ", D, "\n\n")
	cat("`plot", "RGB"[threeTiles], 
		"(openmap(x,path=\"", D, "\"))`\n\n", 
    sep='')
  cat(openmapAttribution(D, 'html'), '\n\n')
	
	for(Dplot in 1:length(mytiles)) {




		oneTile = grep(paste("^", Dsub, "$", sep=""), 
				names(mytiles[[Dplot]]), value=TRUE)
		threeTiles = grep(paste("^", Dsub, 
						"([rR]ed|[gG]reen|[bB]lue)$", sep=""), 
				names(mytiles[[Dplot]]),value=TRUE)


		if(length(threeTiles)==3) { # plotRGB
		map.new(mytiles[[Dplot]])
			
			thetry = try(plotRGB(mytiles[[Dplot]][[
								paste(Dsub, c("Red","Green","Blue"),sep="")
								]],add=TRUE))
			if(class(thetry)=="try-error"){
				print(paste(Dsub, c("Red","Green","Blue"),sep=""))
				print(mytiles[[Dplot]][[paste(Dsub, c("Red","Green","Blue"),sep="")]])
			}
	
	
		} else if (length(oneTile)==1){
		map.new(mytiles[[Dplot]])
			try(plot(mytiles[[Dplot]][[oneTile]],add=TRUE))

		} else {

			plot.new()
			text(0.5, 0.8, paste(D, "is\n not currently\navailable"))
		
		}
#	cat("\n\\end{minipage}&", #"\\begin{minipage}{0.3\\textwidth}",
#			"\n")	
	}
#	cat("\n\\end{minipage}\n")
#	cat("\n\\end{tabular}\n")
	
	
}

```
