<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{backsolveBatch}
-->


```{r setup, include=FALSE}
library('gpuR')
```


## backsolve function test
```{r  test_check}
Nglobal = c(64L, 64L, 4L)
Nlocal = c(4L, 4L, 4L)
NlocalCache = 18

```


```{r  test_check2}

D1 = matrix( 1:160, nrow=40, ncol=40, byrow = TRUE) 
D1[upper.tri(D1)] <- 0
diag(D1)<-1
C1 = matrix( 1:40, nrow=40, ncol=1, byrow = TRUE) 
temp1 = D1%*%C1

gpuD2<-vclMatrix(rbind(D1,D1,D1,D1),nrow=160, ncol=40, type="double")
gpuC2 <- vclMatrix(0, nrow=160, ncol=1, type="double")
gputemp1 <- vclMatrix(temp1,nrow=40, ncol=1, type="double")

gpuRandom::backsolveBatch(gpuC2, gpuD2, gputemp1, 
                                 1L, diagIsOne=TRUE, Nglobal, Nlocal, NlocalCache)
as.matrix(gpuC2)
```



```{r two_function_test2}
a1 = matrix( c(3, 0,0,0, 3,0, 3, 66, 3), nrow=3, ncol=3, byrow = TRUE) 
a2 = matrix( c(1, 0,0,6, 1,0, 18, 8, 1), nrow=3, ncol=3, byrow = TRUE) 

c1 = matrix( c(26, 41, 6), nrow=3, ncol=1, byrow=F) 

b1 = a1%*%c1
c2=solve(a2,b1)

A <- rbind(a1,a2)
#A
B <- b1
#B
C <- rbind(c1,c2)
C
gpuA <- vclMatrix(A, type="double")
gpuB <- vclMatrix(B, type="double")
gpuC <- vclMatrix(0,nrow=6, ncol=1, type="double")  
gpuC2 <- vclMatrix(0,nrow=6, ncol=1, type="double")
#gpuRandom:::backsolveBatchBackend(gpuC, gpuA, gpuB, c(0,3,2,2),c(0,3,0,3),c(0,3,0,2),2L,
#                                  diagIsOne=FALSE, Nglobal, Nlocal, NlocalCache)
#as.matrix(gpuC)
gpuRandom::backsolveBatch(gpuC2, gpuA, gpuB, numbatchB=1L, diagIsOne=FALSE, Nglobal=c(8L,8L,4L), Nlocal=Nlocal, NlocalCache=NlocalCache)
as.matrix(gpuC2)

gpuRandom:::backsolveBatchBackend(gpuC, gpuA, gpuB, 
                                  c(0,3,0,1),c(0,3,0,3),c(0,3,0,1),1L,
                                  diagIsOne=FALSE, Nglobal, Nlocal, NlocalCache)
as.matrix(gpuC)

```


```{r test_preparation}
library(gpuR)
library(geostatsp)
n=40
mydat = SpatialPointsDataFrame(
	cbind(runif(n), seq(0,1,len=n)), 
	data=data.frame(cov1 = rnorm(n), cov2 = rpois(n, 2))
	)

# simulate a random field
set.seed(1)
mydat@data= cbind(mydat@data , RFsimulate(model=c(variance=1.5,range=0.5,nugget=0.25,shape=1.25,anisoRatio = 1, anisoAngleRadins=0),x=mydat)@data)

# add fixed effects
mydat$Y = -3 + 0.5*mydat$cov1 + 0.2*mydat$cov2 + mydat$sim + rnorm(length(mydat), 0, sd=sqrt(0.25))

# fit the model
myres = likfitLgm(
	formula=Y ~ cov1 + cov2, 
	data=mydat, 
	param=c(variance=1.5,range=0.5,nugget=0.25,shape=1.25)
	)

workgroupSize=c(16,16,1)
localSize = c(2,2,1)
NlocalCache=50
```


```{r  test21}
y<-vclMatrix(as.matrix(mydat$Y),type="double")
X<-vclMatrix(as.matrix(cbind(c(rep(1, n)),mydat$cov1,mydat$cov2)),type="double")
coordsGpu<-vclMatrix(mydat@coords,type="double")
paramsBatch = rbind(
c(shape=1.25, range=0.5, variance = 1.5, nugget = 0.25, anisoRatio = 1, anisoAngleRadians = 0),
c(shape=1.25, range=0.5, variance = 1.5, nugget = 0.25, anisoRatio = 1, anisoAngleRadians = 0),
c(shape=1.25, range=0.5, variance = 1.5, nugget = 0.25, anisoRatio = 1, anisoAngleRadians = 0),
c(shape=1.25, range=0.5, variance = 1.5, nugget = 0.25, anisoRatio = 1, anisoAngleRadians = 0))


paramsBatch = t(apply(paramsBatch, 1, geostatsp::fillParam));    paramsBatch
paramsBatch = vclMatrix(cbind(paramsBatch, matrix(0, nrow(paramsBatch), 22-ncol(paramsBatch))),type="double")

betas<-vclMatrix(as.matrix(myres$summary[c("(Intercept)","cov1","cov2"),1]),type="double")

Vbatch = vclMatrix(0, nrow(paramsBatch)*nrow(y), nrow(y), type="double")
diagMat = vclMatrix(0, nrow(paramsBatch), ncol(Vbatch), type = "double")


 rowbatch = nrow(paramsBatch)
 colbatch = ncol(y)
 n = nrow(y)
 p = ncol(X)
     

# ##########################loglik########################################################

    #1, Vbatch=LDL^T, cholesky decomposition
gpuRandom:::maternBatchBackend(Vbatch, coordsGpu, paramsBatch,  workgroupSize, localSize)
gpuRandom::cholBatch(Vbatch, diagMat, numbatchD=rowbatch, Nglobal=workgroupSize, Nlocal=localSize, NlocalCache=NlocalCache)

    
    
    
    #2, temp = y-X*beta
    temp <- y - gpuRandom::gemmBatch(X, betas, rowbatch, 1L, colbatch, need_transpose = FALSE, workgroupSize)
    #tempcpu<-as.matrix(temp)
    
    #3, L * C = temp, backsolve for C
    C <- vclMatrix(0, nrow(Vbatch), ncol(temp), type = gpuR::typeof(Vbatch))
    
    gpuRandom::backsolveBatch(C, Vbatch, temp, numbatchB=1L,  diagIsOne=TRUE,
                          workgroupSize,  localSize,  NlocalCache)
   
   
    Ccpu<-as.matrix(C)
    
    
```



```{r  test22}
y<-vclMatrix(as.matrix(mydat$Y),type="double")
X<-vclMatrix(as.matrix(cbind(c(rep(1, n)),mydat$cov1,mydat$cov2)),type="double")
coordsGpu<-vclMatrix(mydat@coords,type="double")

paramsBatch = rbind( 
c(shape=1.25, range=0.5, variance = 1.5, nugget = 0.25, anisoRatio = 1, anisoAngleRadians = 0))

paramsBatch = t(apply(paramsBatch, 1, geostatsp::fillParam));    paramsBatch
paramsBatch = vclMatrix(cbind(paramsBatch, matrix(0, nrow(paramsBatch), 22-ncol(paramsBatch))),type="double")

betas<-vclMatrix(as.matrix(myres$summary[c("(Intercept)","cov1","cov2"),1]),type="double")

Vbatch = vclMatrix(0, nrow(paramsBatch)*nrow(y), nrow(y), type="double")
diagMat = vclMatrix(0, nrow(paramsBatch), ncol(Vbatch), type = "double")
 
rowbatch = nrow(paramsBatch)
 colbatch = ncol(y)
 n = nrow(y)
 p = ncol(X)
     
# ##########################loglik########################################################

    #1, Vbatch=LDL^T, cholesky decomposition
gpuRandom:::maternBatchBackend(Vbatch, coordsGpu, paramsBatch,  workgroupSize, localSize)
gpuRandom::cholBatch(Vbatch, diagMat, numbatchD=rowbatch, Nglobal=workgroupSize, Nlocal=localSize, NlocalCache=NlocalCache)

 
    #2, temp = y-X*beta
    temp <- y - gpuRandom::gemmBatch(X, betas, rowbatch, 1L, colbatch, need_transpose = FALSE, workgroupSize)
    #tempcpu<-as.matrix(temp)
    
    #3, L * C = temp, backsolve for C
    C <- vclMatrix(0, nrow(Vbatch), ncol(temp), type = gpuR::typeof(Vbatch))
    
    gpuRandom::backsolveBatch(C, Vbatch, temp, numbatchB=1L,  diagIsOne=TRUE,
                          workgroupSize,  localSize,  NlocalCache)
   
    Ccpunew<-as.matrix(C)
    
    Ccpunew-Ccpu[1:40]
```
















```{r test3}
a1 = matrix( c(5, 0,0,2, 5,0, 5, 66, 5), nrow=3, ncol=3, byrow = TRUE) 
a2 = matrix( c(1, 0,0,6, 1,0, 18, 8, 1), nrow=3, ncol=3, byrow = TRUE) 
A1 = cbind(c(0,0,0,0), rbind(c(0,0,0), a1))  #4x4
A2 = cbind(c(0,0,0,0), rbind(c(0,0,0), a2))
C1 = matrix( c(11, 22, 33, 44, 55, 66), nrow=3, ncol=2, byrow=F) 
C2 = matrix( c(6, 5, 4, 3, 2, 1), nrow=3, ncol=2,byrow=F)  

B1 = a1%*%C1
B2= a2%*%C2
BN1 <- rbind(cbind(c(0,0,0),B1,c(0,0,0)), c(0,0,0,0), c(0,0,0,0))
BN2 <- rbind(cbind(c(0,0,0),B2,c(0,0,0)), c(0,0,0,0), c(0,0,0,0))
A <- rbind(A1,A2)
A
B <- rbind(BN1,BN2)
B
C <- rbind(C1,C2)
C
gpuA <- vclMatrix(A, type="double")
gpuB <- vclMatrix(B, type="double")
gpuC <- vclMatrix(0,nrow=6, ncol=3, type="double")  #gpuC2 <- vclMatrix(0,nrow=6, ncol=2, type="double")
gpuRandom:::backsolveBatchBackend(gpuC, gpuA, gpuB, 
                                  c(0,3,0,2),c(1,3,1,3),c(0,3,1,2),2L,
                                  diagIsOne=FALSE, Nglobal, Nlocal, NlocalCache)
as.matrix(gpuC)

```





```{r testP}
N = 4

oneLwer = matrix(0, N, N)
oneLwer[lower.tri(oneLwer, diag=FALSE)] = 1

Amat = vclMatrix(rbind(diag(N), 
                       4*diag(N), 
                       diag(N) + 0.5*oneLwer,
                       2*diag(N) - 0.5*oneLwer),
                 type='double')
Nmatrix = nrow(Amat)/ncol(Amat)
Bmat = vclMatrix(cbind(rep(c(1,0), c(1, N-1)),
             rep(1,N)), type='double')
Cmat = vclMatrix(0, nrow(Amat), ncol(Bmat), type='double')
as.matrix(Amat)
as.matrix(Bmat)

NlocalCache = 10
Nglobal = c(5L, 5L, 5L)
Nlocal = c(1L, 1L) 
gpuRandom:::backsolveBatchBackend(Cmat, Amat, Bmat, 
                                  c(0,N,0,ncol(Bmat)),
                                  c(0,N,0,N),
                                  c(0,N,0,ncol(Bmat)),
                                  1L,
                                  diagIsOne=FALSE, 
                                  Nglobal, Nlocal, NlocalCache)
for(D in 1:Nmatrix) {
print(cbind(
  as.matrix(Amat)[(D-1)*N + 1:N, ], NA,
#  as.matrix(Bmat), NA,
  as.matrix(Cmat)[(D-1)*N + 1:N,], NA,
  solve(as.matrix(Amat)[(D-1)*N + 1:N, ]) %*% as.matrix(Bmat)))
}
```
