<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Fisher test}
-->

`https://github.com/clMathLibraries/clRNG`


## Fisher test simulation

```{r date}
date()
```


```{r packages, results='hide'}
library('gpuR')
```

```{r memoryAvailable, echo=TRUE, results='hide'}
setContext(   grep('OpenCL 2.1', listContexts()$platform)[1]    )
gpuInfo()$deviceName   #gpuInfo()$maxAllocatableMem/(1024^3)
```






Example 1
```{r, eval=TRUE}
x<- matrix(c(2, 5, 15, 3), nrow = 2)

fisher.test(x, alternative = "t",  simulate.p.value = T, B = 1e5)

Nglobal = c(64,16)
streams = gpuR::vclMatrix(gpuRandom::CreateStreams(prod(Nglobal)))
streams2 = deepcopy(streams)


x<-vclMatrix(x,type="integer")
res1 = gpuRandom::fisher.sim(x, 200000L, returnStatistics=FALSE, 
                             type="double", streams=streams, workgroupSize = Nglobal)

 
res1
#as.vector(res1$sim)
#hist(as.vector(res1$sim))
```

```{r ex2, eval=T}
##using the same stream
res2 = gpuRandom::fisher.sim(x, 200000L, returnStatistics=FALSE, 
                             type="double", streams=streams2, workgroupSize = Nglobal)
as.matrix(streams2[1:4,1:4])
res2$p.value
```




example 3
```{r eg3, eval=TRUE}
#compare results with R fisher function
Job <- matrix(c(1,2,1,0, 3,3,6,1, 10,10,14,9, 6,7,12,11), 4, 4)
fisher.test(Job, simulate.p.value = TRUE, B = 1e5) # also close to 0.78


Job<-vclMatrix(Job, type="integer")
result3<-gpuRandom::fisher.sim(Job, 1e5, returnStatistics=FALSE, 
                             type="double", streams=streams, workgroupSize = Nglobal)
result3
```













Example 4
```{r  teaTasting, eval=F}
TeaTasting <-matrix(c(3, 1, 1, 3),nrow=2)

TeaTasting
## Using the R function 
fisher.test(TeaTasting, alternative = "t",  simulate.p.value = TRUE, B = 1e5)


Nglobal = c(16,64)
streams = gpuR::vclMatrix(gpuRandom::CreateStreams(prod(Nglobal)))

TeaTasting<-vclMatrix(TeaTasting,type="integer")
result<-gpuRandom::fisher.sim(TeaTasting, 100000L, returnStatistics=FALSE, 
                             type="double", streams=streams, workgroupSize = Nglobal)

result$p.value
```





```{r eg4, eval=F}
Nglobal = c(64,64)
streams<-vclMatrix(gpuRandom::CreateStreams(prod(Nglobal)))

set.seed(120)
atable<-matrix(as.integer(stats::runif(600,0,1000)), nrow=100, ncol=6)
atable[1:6,]



system.time(fisher.test(atable, simulate.p.value = TRUE, B = 1e5))  ##72.596s on cpu, 250.825s on my cpu

atable<-vclMatrix(atable, type="integer")
res5<-gpuRandom::fisher.sim(atable, 100000L, returnStatistics=FALSE, streams=streams, type="double", 
                            workgroupSize = Nglobal,verbose=F)


res5$p.value
res5$counts
#system.time(gpuRandom::fisher.sim(atable, 100000000L, returnStatistics=FALSE, streams=streams,
                            # type="double", workgroupSize = Nglobal))#171.8


```



```{r data, echo=FALSE,  results="hide",  eval=F}
exampleone<- read.csv("/home/ruoyong/paper2/try1.csv")
exampleone<-exampleone[,-1]
exampleone<-data.matrix(exampleone)
```

```{r Timecompare1, eval=F}
Nglobal<-c(128,64)
streams = gpuR::vclMatrix(gpuRandom::CreateStreams(prod(Nglobal)))

system.time(fisher.test(exampleone,simulate.p.value = TRUE,B=1e7))

exampleone<-vclMatrix(exampleone,type="integer")
system.time(gpuRandom::fisher.sim(exampleone, 10000000L, returnStatistics=FALSE, 
                       type="double", streams=streams, 
                       workgroupSize = Nglobal, verbose=TRUE))
```








