<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{gemmBatch}
-->


```{r setup, include=FALSE}
library('gpuR')
```

## matrices in batch




## matrices in batch both row and col

```{r A and B}
## Arowbatch=4, Acolbatch=2
a11 = matrix(c(15,20,25,14,12,23), ncol=3, nrow=2)
a21 = matrix(c(4,20,6,1,2,7), ncol=3, nrow=2)
a31 = matrix(c(12,18,25,17,20,13), ncol=3, nrow=2)
a41 = matrix(c(1,3,2,7,10,15), ncol=3, nrow=2)
a12 = matrix(c(5,1,6,10,12,9), ncol=3, nrow=2)
a22 = matrix(c(4,20,6,1,2,7), ncol=3, nrow=2)
a32 = matrix(c(12,8,52,7,2,3), ncol=3, nrow=2)
a42 = matrix(c(11,3,2,7,10,15), ncol=3, nrow=2)
A1<- rbind(a11,a21,a31,a41)  #8*3
A2<- rbind(a12,a22,a32,a42)
A<-cbind(A1,A2)
A

a11t=t(a11)
a21t=t(a21)
a31t=t(a31)
a41t=t(a41)
a12t=t(a12)
a22t=t(a22)
a32t=t(a32)
a42t=t(a42)
A1t<- rbind(a11t,a21t,a31t,a41t)  #8*3
A2t<- rbind(a12t,a22t,a32t,a42t)
At<- cbind(A1t,A2t)  #12*4


# Browbatch=4, Bcolbatch=2
b11<-matrix(c(7,1,3,2,3,6,45,5,2,7,66,4), nrow=3, ncol=4)
b21<-matrix(c(2,12,13,5,4,1,25,9,26,3,28,1), nrow=3, ncol=4)
b31<-matrix(c(17,10,1,22,5,0,4,15,3,8,2,9), nrow=3, ncol=4)
b41<-matrix(c(4,0,1,5,2,8,7,9,22,10,6,3), nrow=3, ncol=4)
B1<-rbind(b11,b21,b31,b41)   #12*4
b12<-matrix(c(2,11,3,2,3,4,5,15,20,17,6,1), nrow=3, ncol=4)
b22<-matrix(c(2,12,13,5,4,1,25,9,26,3,28,1), nrow=3, ncol=4)
b32<-matrix(c(17,10,1,22,5,0,4,15,3,8,2,9), nrow=3, ncol=4)
b42<-matrix(c(4,0,1,5,2,8,7,9,22,10,6,3), nrow=3, ncol=4)
B2<-rbind(b12,b22,b32,b42)   #12*4
B<- cbind(B1,B2)  #12*8
B
gpuA<-vclMatrix(A,type="float")
gpuB<-vclMatrix(B,type="float")
gpuAt<-vclMatrix(At,type="float")
```


```{r test transpose, echo=TRUE, eval=T}
outputC<-vclMatrix(0, nrow=8, ncol=8, type="float")
Nglobal = c(16,8,4) 

gpuRandom:::gemmBatchBackend(gpuA, gpuB, outputC, 4L, 4L,2L, 2L, FALSE, Nglobal)
as.matrix(outputC)



outputC2<-vclMatrix(0, nrow=8, ncol=8, type="float")
gpuRandom:::gemmBatchBackend(gpuAt, gpuB, outputC2, 4L, 4L,2L, 2L, TRUE, Nglobal)
as.matrix(outputC2)


a11%*%b11
a21%*%b21
a12%*%b12
a22%*%b22
a41%*%b41
a42%*%b42
a42%*%b41
```



```{r test one vs multiple col, echo=TRUE, eval=T}
gpuB1<-vclMatrix(B1,type="float")
gpuA1<-vclMatrix(A1, type="float")
gpuA1t<-vclMatrix(A1t, type="float")
#outputC3<-vclMatrix(0, nrow=8, ncol=8, type="float")
#gpuRandom:::gemmBatchBackend(gpuA, gpuB1, outputC3, 4L, 2L, 1L, FALSE, Nglobal)
#as.matrix(outputC3)

C4<-gpuRandom::gemmBatch(gpuA, gpuB1, 4L, 4L,2L, 1L, FALSE, Nglobal)
as.matrix(C4)

C5<-gpuRandom::gemmBatch(gpuA1, gpuB, 4L, 4L,1L, 2L, FALSE, Nglobal)
as.matrix(C5)

C6<-gpuRandom::gemmBatch(gpuA1t, gpuB, 4L, 4L, 1L, 2L, TRUE, Nglobal)
as.matrix(C6)

a11%*%b11
a12%*%b11
a21%*%b21
a21%*%b22
a41%*%b41
a41%*%b42
```




```{r test one vs multiple row, echo=TRUE, eval=T}
## Arowbatch=4, Acolbatch=2     2x3
a11 = matrix(c(15,20,25,14,12,23), ncol=3, nrow=2)
a21 = matrix(c(4,20,6,1,2,7), ncol=3, nrow=2)
a31 = matrix(c(12,18,25,17,20,13), ncol=3, nrow=2)
a41 = matrix(c(1,3,2,7,10,15), ncol=3, nrow=2)
a12 = matrix(c(5,1,6,10,12,9), ncol=3, nrow=2)
a22 = matrix(c(4,20,6,1,2,7), ncol=3, nrow=2)
a32 = matrix(c(12,8,52,7,2,3), ncol=3, nrow=2)
a42 = matrix(c(11,3,2,7,10,15), ncol=3, nrow=2)
A1<- rbind(a11,a21,a31,a41)  #8*3
A2<- rbind(a12,a22,a32,a42)
A<-cbind(A1,A2)
A

## Browbatch=1, Bcolbatch=2    3x4
b11<-matrix(c(7,1,3,2,3,6,45,5,2,7,66,4), nrow=3, ncol=4)
b12<-matrix(c(2,11,3,2,3,4,5,15,20,17,6,1), nrow=3, ncol=4)
B<- cbind(b11,b12)  #12*8
gpuB<-vclMatrix(B,type="float")
gpuA<-vclMatrix(A, type="float")

outputC<-vclMatrix(0, nrow=8, ncol=8, type="float")
Nglobal = c(16,8,4) 

C4<-gpuRandom::gemmBatch(gpuA, gpuB, 4L, 1L,2L, 2L, FALSE, Nglobal)
as.matrix(C4)

C5<-gpuRandom::gemmBatch(gpuA1, gpuB, 4L, 4L,1L, 2L, FALSE, Nglobal)
as.matrix(C5)

C6<-gpuRandom::gemmBatch(gpuA1t, gpuB, 4L, 4L, 1L, 2L, TRUE, Nglobal)
as.matrix(C6)

a11%*%b11
a12%*%b12
a21%*%b11
a22%*%b12
a41%*%b11
a42%*%b12
```







```{r testBatcchLocal, eval=FALSE}
library("gpuRandom")
dimA = c(8,8)
dimB = c(10,8)
gpuA = vclMatrix(matrix(seq(1, prod(dimA)), 
                        dimA[1], dimA[2]), type='float')
gpuB = vclMatrix(matrix(10*(1:prod(dimB)), dimB[1], dimB[2]), type='float')

outputCp = vclMatrix(matrix(-1, 10, 10), type='float')

SsubA = c(0,2,4,0,3,4) # A [rowStart, nRowsSub, nRowsTotal, colStart, ...]
SsubB = c(0,3,4,0,4,4) #B

gemmBatch2backend(
  gpuA, gpuB, outputCp,
  c(0,0,0), # transposeA, transposeB, transposeC
  SsubA, SsubB,
  c(0,SsubA[2],5,0,SsubB[5],5), #C
  c(2,2,0,0,0,0), # batches: nRow, nCol, recycleArow, recycleAcol, recycleB row col
  c(2,4,4,1,2,2), #workgroupSize  global 0 1 2, local 0 1 2  
  c(16,16), # cacheSizeA, cacheSizeB,                
  TRUE # verbose
  )
as.matrix(gpuA)
as.matrix(gpuB)
as.matrix(outputCp)#[1:2,1:4]
Dmatrix = c(2,2)-1
AA = as.matrix(gpuA[seq(Dmatrix[1]*SsubA[3] + SsubA[1]+1, len=SsubA[2]),
               seq(Dmatrix[2]*SsubA[6] + SsubA[4]+1, len=SsubA[5])])
BB = as.matrix(gpuB[seq(Dmatrix[1]*SsubB[3] + SsubB[1]+1, len=SsubB[2]),
               seq(Dmatrix[2]*SsubB[6] + SsubB[4]+1, len=SsubB[5])] )
AA
BB
(AA) %*% (BB)
```


```{r testBatcchLocal2, eval=FALSE}
library("gpuRandom")
library("gpuR")
dima = c(3,6)
dimb = c(6,4)

a11=matrix(seq(1, prod(dima)), dima[1], dima[2])
a21=matrix(2*seq(1, prod(dima)), dima[1], dima[2])
b11=matrix(seq(1, prod(dimb)), dimb[1], dimb[2])
b21=matrix(2*seq(1, prod(dimb)), dimb[1], dimb[2])

zerorow=integer(dima[2])
zerocol=integer(dima[1]+2)


A11= cbind(zerocol,rbind(zerorow,a11,zerorow))
A21= cbind(zerocol,rbind(zerorow,a21,zerorow))
zerorow=integer(dimb[2])
zerocol=integer(dimb[1]+2)
B11= cbind(rbind(zerorow,zerorow,b11),zerocol)
B21= cbind(rbind(zerorow,zerorow,b21),zerocol)


gpuA = vclMatrix(rbind(A11,A21), type='float')
gpuB = vclMatrix(rbind(B11,B21), type='float')

outputCp = vclMatrix(matrix(-22, 10, 6), type='float')   # 3x4  3x4

SsubA = c(1,dima[1],5,1,dima[2],7) # A [rowStart, nRowsSub, nRowsTotal, colStart, ...]
SsubB = c(2,dimb[1],8,0,dimb[2],5) #B

gemmBatch2backend(
  gpuA, gpuB, outputCp,
  c(0,0,0), # transposeA, transposeB, transposeC
  SsubA, SsubB,
  c(0,SsubA[2],5,  0,SsubB[5],ncol(outputCp)/2), #C
  c(2,1,0,0,0,0), # batches: nRow, nCol, recycleArow, recycleAcol, recycleB row col
  c(2,4,4,1,2,2), #workgroupSize  global 0 1 2, local 0 1 2  
  c(16,16), # cacheSizeA, cacheSizeB,                
  TRUE # verbose
  )

as.matrix(outputCp)
rbind(a11%*%b11,a21%*%b21)
```



