<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{loglikelihood_lgm}
-->


```{r setup, include=FALSE}
library(geostatsp)
set.seed(1)
n=20
mydat = SpatialPointsDataFrame(cbind(stats::runif(n), seq(0,1,len=n)),
                               data=data.frame(cov1 = stats::rnorm(n), cov2 = stats::rpois(n, 2)))

# simulate a random field
mydat@data= cbind(mydat@data , RFsimulate(model=c(variance=1.5,range=0.5,nugget=0.25,shape=1.25,anisoRatio = 1, anisoAngleRadins=0),x=mydat)@data)

# add fixed effects
# exponentiate to make positive and enable boxcox
mydat$Y = -3 + 0.5*mydat$cov1 + 0.2*mydat$cov2 + mydat$sim + stats::rnorm(length(mydat), 0, sd=sqrt(0.25))
mydat$Yexp = exp(mydat$Y)
```


```{r patrickTest, eval=F}
library(gpuR)

params = rbind(c(shape=1.25, range=0.2641423, variance = 1.5, nugget = 0, anisoRatio = 1, anisoAngleRadians = 0),
                    c(shape=1.25, range=0.5, variance = 1.5, nugget = 0.25, anisoRatio = 1, anisoAngleRadians = 0),
                    c(shape=2.25, range=0.5, variance = 2.5, nugget = 2.25, anisoRatio = 1, anisoAngleRadians = 0))
 # c(shape=1.25, range=0.5, variance = 1.5, nugget = 0.25, anisoRatio = 1, anisoAngleRadians = 0))
#paramsBatch = rbind(c(shape=3, range=11.5247874, variance = 5.5, nugget = 0.6932729, anisoRatio = 1, anisoAngleRadians = 0))


x = mydat
boxcox = c(0, 0.5)
Scov = c('cov1','cov2')
yvar = 'Yexp'
NparamPerIter = 3

workgroupSize = c(1,1,1)
  localSize = c(1,1,1)
NlocalCache=500
type='double'
verbose = 9L


if(boxcox[1] != 1) {
  boxcox = c(1, 0, setdiff(boxcox, c(0,1)))
}
Ncov = length(Scov)+1
Ndata = length(boxcox)
Nparam = nrow(params)

paramsBatch1 = t(apply(params, 1, geostatsp::fillParam))
paramsBatch = vclMatrix(
  cbind(paramsBatch1, matrix(0, nrow(paramsBatch1), 22-ncol(paramsBatch1))),
  type=type)

yx = vclMatrix(cbind(
  as.vector(x@data[,yvar]),
  matrix(0, nrow(x@data), length(boxcox)-1),
  1,
  as.matrix(x@data[,Scov])
), type=type)
coords = vclMatrix(x@coords, type =type)

boxcoxGpu = vclVector(boxcox, type=type)
betas = vclMatrix(0, Nparam, Ncov * Ndata, type=type)
detVar = vclVector(0, Nparam,type=type)
detReml = vclVector(0, Nparam, type=type)
jacobian = vclVector(0, Ndata, type=type)
ssqY <- vclMatrix(0, Nparam, Ndata, type=type)
ssqX <- vclMatrix(0, Nparam, Ndata, type=type)

# objects for debugging
ssqYX = vclMatrix(0, ncol(yx) * NparamPerIter, ncol(yx), type=type)
LinvYX = vclMatrix(0, nrow(yx) * NparamPerIter, ncol(yx), type=type)
QinvSsqYx = vclMatrix(0, NparamPerIter*Ncov, Ndata, type = type);
varMat = vclMatrix(0, nrow(yx)*NparamPerIter, nrow(coords), type=type)
cholXVXdiag = vclMatrix(0, NparamPerIter, Ndata, type=type)


gpuRandom:::likfitGpu_BackendP(
  yx,
  coords,
  paramsBatch,
  boxcoxGpu,
  betas,
  ssqY,
  ssqX,
  detVar,
  detReml,
  jacobian,
  NparamPerIter,
  workgroupSize,
  localSize,
  NlocalCache,
  verbose = 10,
  ssqYX, LinvYX,QinvSsqYx,cholXVXdiag
)

dim(ssqYX)

varMatCpu = geostatsp::matern(
  mydat, params[1,])

as.matrix(ssqYX)[1:ncol(ssqYX),]
t(as.matrix(yx)) %*% solve(varMatCpu) %*% as.matrix(yx)

determinant(varMatCpu, logarithm=TRUE)$modulus
as.vector(detVar)

theChol = chol(varMatCpu)
theDiags = diag(theChol)
theCholL = theChol %*% diag(1/theDiags)
LinvYxCpu = solve(theCholL) %*% as.matrix(yx)

recoverVar = theCholL %*% diag(theDiags^2) %*% t(theCholL)
range(recoverVar - varMatCpu)

LinvYxCpu[1:4,]
as.matrix(LinvYX)[1:4,]

as.vector(detVar)
as.vector(detReml)
as.matrix(ssqX)
as.matrix(ssqY)
as.matrix(QinvSsqYx)
as.matrix(cholXVXdiag)

#as.vector(jacobian)
#head(as.matrix(yx)) 
```



```{r OLDtest_on_cpu, message=FALSE, eval=T}
#dist(mydat@coords)
# fit the model
myres = likfitLgm(
	formula=Y ~ cov1 + cov2, 
	data=mydat, 
	param=c(variance=1.5,range=0.5, shape=1.25, nugget=0.25), reml=FALSE)
#variance parameter and regression coefficients are always estimated even if not listed.
# produces mles of parameters
myres$parameters
myres$summary[c("(Intercept)","cov1","cov2"),1] 


# calculate log-likelihood
temp0=loglikLgm(param=myres$parameters, 
		data=mydat, 
		formula = Y ~ cov1 + cov2,
		reml=FALSE, minustwotimes=TRUE)
temp0
#minusTwoLogLik 
#      52.20254 

#52.20254-56.21288=-4.01034


 #53.73501 -72.85779 = -19.12278

```



```{r oldTest, eval=FALSE}
betas<-vclMatrix(as.matrix(myres$summary[c("(Intercept)","cov1","cov2"),1]),type="double")

workgroupSize=c(64,16,16)
localSize = c(4,4,1)
workgroupSize = localSize = c(1,1,1)
NlocalCache=500

BoxCox = c(1, 0, 0.5)







temp1=likfitGpu(modelname = myres,
                           mydat = mydat, type="double", 
                    bigparamsBatch = paramsBatch,betas = betas,form="loglik",
                    BoxCox = 1, groupsize = 1,
                    workgroupSize=workgroupSize,localSize=localSize, NlocalCache=NlocalCache,
                    verbose=1L)

modelname = myres
type='double'
bigparamsBatch = paramsBatch
BoxCox = 1
groupsize = 1
  form = c(loglik=1, ml=2, mlFixSigma=3, mlFixBeta=4, reml=5, remlPro=6)['loglik']
  
  output1 <- lgmGpuObjectes1(modelname, mydat, type=type)
  colbatch<- length(BoxCox)+1   
  
  yXcpu <- output1$yXcpu
  
  # get jacobian matrix
  jacobian = -2*(BoxCox-1)* sum(log(yXcpu[,1])) 
  closetooneindex <- which(abs(BoxCox - 1 ) < 0.001)
  jacobian[closetooneindex] = 0    
  jacobian <- c(jacobian, 0)   
  jacobian<- vclMatrix(matrix(jacobian, nrow=groupsize, ncol=length(jacobian), byrow=TRUE), type=type) # make it from a vector to a matrix!!!
  
  
  # box cox transform   
  transformed_y = matrix(0,output1$n,length(BoxCox))    
  for (i in 1:length(BoxCox)){
    transformed_y[ ,i] <- ((yXcpu[ ,1]^BoxCox[i]) - 1)/BoxCox[i]
  }      
  closetozeroindex <- which(abs(BoxCox)<0.001)
  if(length(closetozeroindex))
    transformed_y[ ,closetozeroindex] = log(yXcpu[,1])     
  yX <- vclMatrix(cbind(transformed_y,yXcpu),type=type)
  
  totalparams <- nrow(bigparamsBatch)
  
  bigvariances <- vclMatrix(matrix(bigparamsBatch[,3], nrow=totalparams, ncol=colbatch, byrow=FALSE), type=type)  
  ssqBetaR <- vclMatrix(0, totalparams, colbatch, type=type)
  ssqXR <- vclMatrix(0, totalparams, colbatch, type=type)
  ssqYR <- vclMatrix(0, totalparams, colbatch, type=type)
  logDR <- vclVector(0, totalparams, type=type)
  logPR <- vclVector(0, totalparams, type=type)
  finalbetahatR <- vclMatrix(0, totalparams*output1$p, colbatch, type=type)
  finalLogLik <- vclMatrix(0, totalparams, colbatch, type=type)
  
  
  gpuRandom:::likfitGpu_Backend(output1$coordsGpu,
                    bigparamsBatch,
                    yX,       # a vclMatrix of n * colbatch
                    betas,
                    bigvariances,  # a vclMatrix of nrow(bigparamsBatch) * colbatch
                    jacobian,      # a vclMatrix of groupsize * colbatch
                    ssqBetaR,      # a vclMatrix
                    ssqXR,        # a vclMatrix
                    ssqYR,        # a vclMatrix
                    logDR,         # a vclVector
                    logPR,         # a vclVector
                    finalbetahatR,      # a vclMatrix
                    finalLogLik,   # a vclMatrix of nrow(bigparamsBatch) * colbatch
                    output1$n, 
                    output1$p, 
                    groupsize,
                    colbatch,
                    form,
                    workgroupSize, 
                    localSize, 
                    NlocalCache)
  as.matrix(bigparamsBatch)  
  as.matrix(logDR)
  

#as.matrix(temp1)
#56.21288

# 72.85779
temp2=gpuRandom::likfitGpu(myres,mydat, type="double", 
            paramsBatch,betas=NULL,form="ml",workgroupSize,localSize, NlocalCache)$minusTwoLogLik
as.matrix(temp2)
# #117.924
 temp3=gpuRandom::likfitGpu(myres,mydat, type="double", 
             paramsBatch,betas,form="mlFixSigma",workgroupSize,localSize, NlocalCache)$minusTwoLogLik
 as.matrix(temp3)
# #50.17793
# 
# temp4=gpuRandom::likfitGpu(myres,mydat, type="double", 
#                            paramsBatch,betas=NULL,form="mlFixBeta",minustwotimes=TRUE,workgroupSize,localSize, NlocalCache)
# as.matrix(temp4)
# #60.14219
# 
# temp5=gpuRandom::likfitGpu(myres,mydat, type="double", 
#                            paramsBatch,betas=NULL,form="reml",minustwotimes=TRUE,workgroupSize,localSize, NlocalCache)
# as.matrix(temp5)
# #67.53707
# 
# temp6=gpuRandom::likfitGpu(myres,mydat, type="double", 
#                            paramsBatch,betas=NULL,form="remlPro",minustwotimes=TRUE,workgroupSize,localSize, NlocalCache)
# as.matrix(temp6)
#66.66792
```






```{r OLDtest_using_cpu_funtions, echo=FALSE, eval=FALSE}
ycpu<-mydat$Y
Xcpu<-as.matrix(cbind(c(rep(1, n)),mydat$cov1,mydat$cov2))
betas<-c(  -2.9630175,  0.6672477,  0.3847218)
betas<- c(-3.0552499, 0.6161210, 0.4188837)
tempcpu2<-ycpu-Xcpu%*%betas

# one batch parameters
paramsBatch = rbind(c(shape=1.25, range=0.2641423, variance = 1.5, nugget = 0, anisoRatio = 1, anisoAngleRadians = 0))
#paramsBatch = rbind(c(shape=3, range=11.5247874, variance = 5.5, nugget = 0.6932729, anisoRatio = 1, anisoAngleRadians = 0))
paramsBatch = t(apply(paramsBatch, 1, geostatsp::fillParam));    paramsBatch

materncpu = geostatsp::matern(
    x=mydat,
    param=drop(paramsBatch[1,1:7])
    )

cholCpu = as.matrix(chol(materncpu))
theDiag = diag(cholCpu)
L = cholCpu %*% diag(1/theDiag)
D = diag(theDiag^2)

# L<-as.matrix(Vbatch)
# library(gdata)
# upperTriangle(L, diag=FALSE, byrow=FALSE) <- 0
# diag(L)<-1

A<-solve(L, tempcpu2)

###C^T * D^(-1) * C
one0<-t(A)%*% solve(D) %*%A


#5, part1 = n*log(sigma^2)+log |D|
logD<-  sum(log(diag(D)))
#logD <- apply(log(D),1,sum)
part1 <-n*log(paramsBatch[,3]) + logD
    
#6,
loglik2 <- part1 + one0/paramsBatch[,3] + n*log(2*pi)


#

#72.85779
```










```{r OLDtest_loop_Feb9,eval=F}
library(gpuRandom)
library(gpuR)
library('geostatsp')
data('swissRain')
sr2 = swissRain[0:25,]

# extract variables for modeling
sr2$sqrtY = sqrt(sr2$rain)
sr2$elev = raster::extract(swissAltitude, sr2)


swissFitIso = geostatsp::likfitLgm(
  data=sr2,
  formula=sqrtY ~ elev,
  param=c(range=50000,shape=1),
  reml=FALSE,
  verbose=FALSE
)

swissFitIso$parameters
#swissFitIso$summary[c("(Intercept)","elev"),1]

#betas<-vclMatrix(as.matrix(swissFitIso$summary[c("(Intercept)","elev"),1]),type="double")




newParamList = list(
  range=seq(30000, 80000 , len=1),
  nugget = seq(0,0.25,len=1)
) 


newParam= do.call(expand.grid, newParamList)

otherparams = c(shape=1, variance = 2.016713, anisoRatio = 1, anisoAngleRadians = 0)
otherparams = matrix(rep(otherparams,each=nrow(newParam)),nrow=nrow(newParam))
colnames(otherparams) <- c("shape","variance", "anisoRatio", "anisoAngleRadians")

paramsBatch0 = cbind(newParam, otherparams)
paramsBatch0 = t(apply(paramsBatch0, 1, geostatsp::fillParam))
paramsBatchcpu = cbind(paramsBatch0, matrix(0, nrow(paramsBatch0), 22-ncol(paramsBatch0)))

#paramsBatch = gpuR::vclMatrix(cbind(paramsBatch0, matrix(0, nrow(paramsBatch0),22-ncol(paramsBatch0))),type="double")

workgroupSize=c(16,16,8)
localSize = c(4,4,1)
NlocalCache=500

system.time(
temp <- likfitGpu(swissFitIso, sr2, type="double", 
                             paramsBatchcpu, #cpu Matrix of parameter sets,
                             betas=NULL, #a vclmatrix  #given by the user or provided from formula
                             BoxCox=c(1.5,2),
                             form = "ml",  
                             groupsize=2,
                             workgroupSize,
                             localSize,
                             NlocalCache))

# 151.580
tempcpu<-as.matrix(temp)

lMatrix = matrix(tempcpu[,3], length(newParamList[[1]]), length(newParamList[[2]]))
# 
myCol = mapmisc::colourScale(lMatrix, breaks=8, dec=0)
image(
  newParamList[[1]]/1000, newParamList[[2]], lMatrix,
  col = myCol$col, breaks=myCol$breaks,
  xlab = names(newParamList)[1],
  ylab = names(newParamList)[2]
)
mapmisc::legendBreaks('topright', myCol)


```




```{r newtest_4.13,eval=F}
library(gpuRandom)
library(gpuR)
library('geostatsp')
data('swissRain')
sr2 = swissRain[0:50,]

# extract variables for modeling
sr2$sqrtY = sqrt(sr2$rain)
sr2$elev = raster::extract(swissAltitude, sr2)


swissFitIso = geostatsp::likfitLgm(
  data=sr2,
  formula=sqrtY ~ elev,
  param=c(range=50000,shape=1),
  reml=FALSE,
  verbose=FALSE
)

swissFitIso$parameters




newParamList = list(
  range=seq(30000, 80000 , len=10),
  nugget = seq(0,0.25,len=10)
) 


newParam= do.call(expand.grid, newParamList)

otherparams = c(shape=1, variance = 2.079408, anisoRatio = 1, anisoAngleRadians = 0)
otherparams = matrix(rep(otherparams,each=nrow(newParam)),nrow=nrow(newParam))
colnames(otherparams) <- c("shape","variance", "anisoRatio", "anisoAngleRadians")

paramsBatch0 = cbind(newParam, otherparams)
paramsBatch0 = t(apply(paramsBatch0, 1, geostatsp::fillParam))
paramsBatch = gpuR::vclMatrix(cbind(paramsBatch0, matrix(0, nrow(paramsBatch0),22-ncol(paramsBatch0))),type="double")

workgroupSize=c(16,16,8)
localSize = c(4,4,1)
NlocalCache=500

#groupsize=10
#BoxCox=2
betas <- vclMatrix(0, nrow=0, ncol= 0,type="double")


system.time(
temp <- gpuRandom::likfitGpu(swissFitIso, sr2, type="double", 
                  paramsBatch, #gpu Matrix of parameter sets,
                  betas, #a vclmatrix  #given by the user or provided from formula
                  BoxCox=2,
                  form = "ml",  
                  groupsize=10,
                  workgroupSize,
                  localSize,
                  NlocalCache))

as.matrix(temp$logD)
as.matrix(temp$logP)
as.matrix(temp$ssqX)
as.matrix(temp$LogLik)
# 151.580
tempcpu<-as.matrix(temp)
tempcpu[1:10,]

lMatrix = matrix(tempcpu[,3], length(newParamList[[1]]), length(newParamList[[2]]))
# 
myCol = mapmisc::colourScale(lMatrix, breaks=8, dec=0)
image(
  newParamList[[1]]/1000, newParamList[[2]], lMatrix,
  col = myCol$col, breaks=myCol$breaks,
  xlab = names(newParamList)[1],
  ylab = names(newParamList)[2]
)
mapmisc::legendBreaks('topright', myCol)


```






```{r NEW CODE TEST}
# isotropic
data('swissRain')
sr2 = swissRain[0:30,]

# extract variables for modeling
sr2$sqrtY = sqrt(sr2$rain)
sr2$elev = raster::extract(swissAltitude, sr2)


swissFitIso = geostatsp::likfitLgm(
  data=sr2,
  formula=sqrtY ~ elev,
  param=c(range=50000,shape=1),
  reml=FALSE,
  verbose=FALSE
)
swissFitIso$parameters
newParamList = list(
  range=seq(30000, 80000 , len=10),
  nugget = seq(0,0.25,len=10)
) 

newParam= do.call(expand.grid, newParamList)

res= mapply(
	function(range, nugget) {
		loglikLgm(
		c(swissFitIso$parameters[c('shape')], 
			range = unname(range), nugget = unname(nugget)),
		data = sr2,
		formula = swissFitIso$model$formula,
		reml = swissFitIso$model$reml,
		minustwotimes=FALSE)
	},
	range = newParam$range,
	nugget = newParam$nugget
	)

lMatrix = matrix(res, length(newParamList[[1]]), length(newParamList[[2]]))

myCol = mapmisc::colourScale(lMatrix, breaks=8, dec=0)
image(
	newParamList[[1]]/1000, newParamList[[2]], lMatrix,
	col = myCol$col, breaks=myCol$breaks,
	xlab = names(newParamList)[1],
	ylab = names(newParamList)[2]	
	)
mapmisc::legendBreaks('topright', myCol)


```






```{r test_4.29,eval=F}
library(gpuRandom)
library(gpuR)
library('geostatsp')
data('swissRain')
sr2 = swissRain[0:30,]

# extract variables for modeling
sr2$sqrtY = sqrt(sr2$rain)
sr2$elev = raster::extract(swissAltitude, sr2)


swissFitIso = geostatsp::likfitLgm(
  data=sr2,
  formula=sqrtY ~ elev,
  param=c(range=50000,shape=1),
  reml=FALSE,
  verbose=FALSE
)

swissFitIso$parameters

newParamList = list(
  range=seq(30000, 80000 , len=20),
  nugget = seq(0,0.25,len=20)
) 


newParam= do.call(expand.grid, newParamList)

otherparams = c(shape=1, variance=1.750759, anisoRatio = 1, anisoAngleRadians = 0)
otherparams = matrix(rep(otherparams,each=nrow(newParam)),nrow=nrow(newParam))
colnames(otherparams) <- c("shape", "variance", "anisoRatio", "anisoAngleRadians")

paramsBatch0 = cbind(newParam, otherparams)
paramsBatch0 = t(apply(paramsBatch0, 1, geostatsp::fillParam))
paramsBatch = gpuR::vclMatrix(cbind(paramsBatch0, matrix(0, nrow(paramsBatch0),22-ncol(paramsBatch0))),type="double")

workgroupSize=c(16,16,8)
localSize = c(4,4,1)
NlocalCache=500


type="double"
p=2
BoxCox=2
betas = vclMatrix(0, nrow=p, ncol=length(BoxCox)+2, type=type)

finalLogLik <- vclMatrix(0, nrow(paramsBatch), length(BoxCox)+2, type=type)



ssqY <- vclMatrix(0, totalnumbersets, colbatch, type = type)
ssqbetahat <- vclMatrix(0, totalnumbersets, colbatch, type = type)
logD<- vclVector(0, length=totalnumbersets,type=type)
logP<- vclVector(0, length=totalnumbersets,type=type)
betahat <- vclMatrix(0, totalnumbersets*p, colbatch, type=type)
ssqYX <- vclMatrix(0, (colbatch+p)*totalnumbersets, (colbatch+p), type=type)



system.time(
gpuRandom::likfitGpu(swissFitIso, sr2, type="double", 
                  paramsBatch, #gpu Matrix of parameter sets,
                  betas=NULL, #a vclmatrix  #given by the user or provided from formula
                  ssqYX,
                  ssqY,
                  ssqbetahat,
                  logD,
                  logP,
                  betahat,
                  finalLogLik,
                  BoxCox,
                  form = "ml",  
                  groupsize=20,
                  workgroupSize,
                  localSize,
                  NlocalCache))



as.vector(logD)
as.vector(logP)
as.matrix(ssqY)[1:10,]
as.matrix(ssqbetahat)[1:10,]
tempcpu<-as.matrix(finalLogLik)

# 151.580

tempcpu[1:10,]

lMatrix = matrix(tempcpu[,2], length(newParamList[[1]]), length(newParamList[[2]]))
# 
myCol = mapmisc::colourScale(lMatrix, breaks=8, dec=0)
image(
  newParamList[[1]]/1000, newParamList[[2]], lMatrix,
  col = myCol$col, breaks=myCol$breaks,
  xlab = names(newParamList)[1],
  ylab = names(newParamList)[2]
)
mapmisc::legendBreaks('topright', myCol)


```
