<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{matrix_add_vector}
-->


```{r test}
library(gpuRandom)
library(gpuR)
type="double"
nrow<-8
ncol<-10
x<-vclMatrix(1:80, nrow=nrow,ncol=ncol, type=type);      xcpu<-matrix(1:80, nrow=nrow,ncol=ncol)

v1<-vclVector(1:8, type=type);        vcpu <- as.vector(v1)
v2<-vclVector(3:12,  type=type);       vcpu <- as.vector(v2)

result <- vclMatrix(0, nrow=nrow,ncol=ncol, type=type)

xcpu 
vcpu

gpuRandom:::matrix_vector_sumBackend(x,v1, result, byrow=TRUE, c(4,4))
as.matrix(result)


```





```{r test2}
library(gpuRandom)
library(gpuR)
type="double"
nrow<-8
ncol<-10
a<-vclMatrix(1:80, nrow=nrow,ncol=ncol, type=type);      acpu<-matrix(1:80, nrow=nrow,ncol=ncol)

b<-vclMatrix(1:8, nrow=nrow, ncol=1, type=type);         bcpu <- as.matrix(b)
#v2<-vclVector(3:12,  type=type);       vcpu <- as.vector(v2)

result <- vclMatrix(0, nrow=nrow,ncol=ncol, type=type)

r<-acpu+bcpu

gpuRandom:::matrix_matrix_sumBackend(a, b, result, c(4,4))
as.matrix(result)


```