<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{matern2021}
-->


```{r setup, include=FALSE}
library(geostatsp)
library(gpuR)
set.seed(1)
n=20
mydat = SpatialPointsDataFrame(cbind(stats::runif(n), seq(0,1,len=n)),
                               data=data.frame(cov1 = stats::rnorm(n), cov2 = stats::rpois(n, 2)))

# simulate a random field
mydat@data= cbind(mydat@data , RFsimulate(model=c(variance=1.5,range=0.5,nugget=0.25,shape=1.25,anisoRatio = 1, anisoAngleRadins=0),x=mydat)@data)

# add fixed effects
# exponentiate to make positive and enable boxcox
mydat$Y = -3 + 0.5*mydat$cov1 + 0.2*mydat$cov2 + mydat$sim + stats::rnorm(length(mydat), 0, sd=sqrt(0.25))
#mydat$Yexp = exp(mydat$Y)



```



```{r}
library(gpuR)
type="double"
params = rbind(c(shape=1.25, range=0.2641423, variance = 1.5, nugget = 0, anisoRatio = 1, anisoAngleRadians = 0),
               c(shape=1.25, range=0.5, variance = 1.5, nugget = 0.25, anisoRatio = 1, anisoAngleRadians = 0),
               c(shape=2.25, range=0.5, variance = 2.5, nugget = 2.25, anisoRatio = 1, anisoAngleRadians = 0))
paramsBatch1 = t(apply(params, 1, geostatsp::fillParam))
paramsBatch = vclMatrix(cbind(paramsBatch1, matrix(0, nrow(paramsBatch1), 22-ncol(paramsBatch1))),type=type)

coords = vclMatrix(mydat@coords, type =type)
groupsize <- nrow(paramsBatch) 



workgroupSize=c(1,1,1)
localSize = c(1,1,1)
#NlocalCache=500

workgroupSize=c(3,3,1)
localSize = c(1,1,1)


workgroupSize=c(6,6,6)
localSize = c(1,1,1)

Vbatch <- vclMatrix(0, groupsize*n, n, type = type)
gpuRandom::maternBatch(Vbatch, coords, paramsBatch,  workgroupSize, localSize)


as.matrix(Vbatch)
dim(Vbatch)



```


