<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Matern correlations}
-->


# Matern correlations
```{r date}
date()
```



```{r packages, results='hide', message='hide'}
   library(gpuR)
   library(gpuRandom)
```


```{r memoryAvailable, echo=TRUE}
listContexts()[,'platform']
which2.1 = grep('OpenCL 2.1',listContexts()[,'platform'])
if(length(which2.1)) {
  setContext(which2.1[1])
}
gpuInfo()$deviceName
gpuInfo()$maxAllocatableMem/(1024^3)
```

Set up spatial data
```{r setupData}
   Nsim = 4
   Ngrid = c(2,4)
   NlocalCache = 300
    NglobalMatern = c(64,8) 
    NlocalMatern = c(8, 4)
   NglobalChol =  c(16,8,4)
    NglobalChol =  c(64,8)
    NlocalChol = c(16, 8)
    NglobalRandom = c(64,4)
  NglobalMult = c(16,4,4)   
  NlocalMult = c(4,4,1)   
theType = "float"


NlocalMatern = c(2,2)


if(gpuR::gpuInfo()$deviceMemory > 10^10){
   Ngrid = c(2,4)
   Nsim = 6
   NlocalCache = 4000
   NglobalMatern = c(256,8) 
   NlocalMatern = c(32, 8)
   NglobalChol =  c(128,8)
   NlocalChol = c(16, 8)
   NglobalRandom = c(512,8)
   NglobalMult = c(64,8,8)   
   NlocalMult = c(8,8,1)
   theType = "double"
}

myRaster = raster::raster( raster::extent(0,Ngrid[1]/Ngrid[2],5,6),Ngrid[1], Ngrid[2])
coordsSp = sp::SpatialPoints(raster::xyFromCell(myRaster, 1:raster::ncell(myRaster)))
#head(coordsSp@coords,15)
#dist(coordsSp@coords)
```



# Batch matern
```{r paramsBatch}
myParamsBatch = rbind(
c(shape=5.99, range=1, variance = 1, nugget = 0, anisoRatio = 1, anisoAngleRadians = 0), 
c(shape=6, range=1, variance = 2, nugget = 0, anisoRatio = 1, anisoAngleRadians = 0),
c(shape=6.01, range=1, variance = 3, nugget = 0, anisoRatio = 1, anisoAngleRadians = 0), 
c(shape=3, range=5, variance = 4, nugget = 0, anisoRatio = 1, anisoAngleRadians = 0))
# c(shape=4, range=5, variance = 1, nugget = 0, anisoRatio = 1, anisoAngleRadians = 0), 
# c(shape=5, range=5, variance = 1, nugget = 0, anisoRatio = 1, anisoAngleRadians = 0) )

myParamsBatch = t(apply(myParamsBatch, 1, geostatsp::fillParam))

#myParamsBatch = myParamsBatch[rep(1, 12),]
```

```{r outputBatchCreate, eval=T}
coordsGpu = vclMatrix(coordsSp@coords, nrow(coordsSp@coords), ncol(coordsSp@coords), type=theType)
outputBatchF = vclMatrix(0, nrow(myParamsBatch)*nrow(coordsGpu), nrow(coordsGpu), type=gpuR::typeof(coordsGpu))

paramsGpu = vclMatrix(cbind(
  myParamsBatch, 
  matrix(0, nrow(myParamsBatch), 22-ncol(myParamsBatch))), type=gpuR::typeof(coordsGpu))

colnames(paramsGpu)= c(colnames(paramsGpu)[1:7],
 c('costheta', 'sintheta','anisoRatioSq',
 ' varscale', 'logxscale', 'sinrat','mu', 'muSq', 'mup1', 'nuround', 'g1', 
 'g2', 'g1pnu', 'g1mnu', 'variancePlusNugget'))


gpuRandom:::maternBatchBackend(
    outputBatchF,
    coordsGpu, 
    paramsGpu,  
    c(1,4),#NglobalMatern, 
    c(1,4),#NlocalMatern,
    startrow = 1,
    numberofrows = 4,
    verbose = 1)
as.matrix(outputBatchF)[,1:6]

geostatsp::matern(
    x=coordsSp,
    param=drop(myParamsBatch[1,1:7])
    )[1:7,1:7]
as.matrix(outputBatchF[1:7,1:7])
geostatsp::matern(
    x=coordsSp,
    param=drop(myParamsBatch[2,1:7])
    )[1:7,1:7]
as.matrix(outputBatchF[ncol(outputBatchF) + (1:7),1:7])
geostatsp::matern(
    x=coordsSp,
    param=drop(myParamsBatch[3,1:7])
    )[1:7,1:7]
as.matrix(outputBatchF[2*ncol(outputBatchF) + (1:7),1:7])
#################
# #upper
# thisx = as.matrix(dist(coordsSp@coords)/5)
# #lower
# ln_half_x = log(thisx/2)
# 
# ####compare
# as.matrix(outputBatchF[1:8,1:8])
# thisx[1:8,1:8]
# as.matrix(outputBatchF[1:8,1:8])
# ln_half_x[1:8,1:8]
# 
# #lower
# lower<-outer(coordsSp@coords[,1], coordsSp@coords[,1], FUN = '-')
# lower[1:8,1:8]
```









```{r batchMaternCompare, include=TRUE, eval=FALSE}
# Compare output to geostatsp's matern


quantile(fromCpu - as.matrix(outputBatchF[1:ncol(outputBatchF),]))


var4cpu = geostatsp::matern(
    x=coordsSp,
    param=drop(myParamsBatch[2,1:7])
    )

var4gpu = as.matrix(outputBatchF[21:40, ])
quantile(var4cpu - var4gpu)
```

# Cholesky
```{r cholBach, eval = F}
diagMat = vclMatrix(0, nrow(paramsGpu), ncol(outputBatchF), type = gpuR::typeof(outputBatchF))

outputChol = vclMatrix(0, nrow(outputBatchF), ncol(outputBatchF), type = gpuR::typeof(outputBatchF))

system.time(gpuRandom::cholBatch(
  outputChol, diagMat, numbatchD=nrow(myParamsBatch),
  Nglobal = NglobalChol,
  Nlocal = NlocalChol,
  NlocalCache = NlocalCache))

as.matrix(outputChol[1:12,1:7])
as.matrix(diagMat[1:12,1:7])
```

```{r cholBatchCpu, include=FALSE, eval=F}
cholCpu = as.matrix(chol(var4cpu))
theDiag = diag(cholCpu)
cholCpu = cholCpu %*% diag(1/theDiag)
theDiag = theDiag^2

chol4gpu = as.matrix(outputChol[seq(1+3*nrow(coordsGpu), len=nrow(coordsGpu)),])
chol4gpu[upper.tri(chol4gpu)] = 0
diag(chol4gpu) = 1

chol4gpu[1:4,1:4]
cholCpu[1:4,1:4]
range(cholCpu - as.matrix(chol4gpu))

range(theDiag - as.matrix(diagMat)[4,])
```

# Multiplying lower triangle


create a matrix of independent normals


```{r randomNormalsSim, eval=F}
set.seed(1)
streams = gpuRandom::CreateStreams(prod(NglobalRandom))
streamsGpu = vclMatrix(streams, type='integer')

zMatGpu = vclMatrix(nrow=as.integer(ncol(outputBatchF) * nrow(myParamsBatch)),
                    ncol=as.integer(Nsim),
                    type = gpuR::typeof(outputBatchF))
dim(zMatGpu)
gpuRandom:::gpuRnBackend(zMatGpu, streamsGpu, NglobalRandom, "normal")
#system.time(gpuRandom:::gpuRnBackend(zMatGpu, streamsGpu, NglobalRandom, "normal"))

```

```{r checkRange, eval=F, include=FALSE}
streams[1:3,1:6]
as.matrix(streamsGpu[1:3,1:6])
zMatCpu = as.matrix(zMatGpu)
hist(zMatCpu)
qqnorm(as.vector(zMatCpu))
```




compute U = L D^(1/2) Z, where LDLt is the Cholesky of the variance matrix, Z is the independent normals

```{r multLowerGpu, eval = F}
simMat = deepcopy(-100*zMatGpu)

system.time(
gpuRandom:::multiplyLowerDiagonalBatchBackend(
  simMat, outputChol, diagMat, zMatGpu,
  diagIsOne = TRUE, # diagonal of L is one
  transformD = "sqrt", # take the square root of each element of D
  Nglobal = NglobalMult,
  Nlocal = NlocalMult,
  NlocalCache = NlocalCache)
)
```



# Plot simulated materns

```{r plotSimNames,eval=F }
theNames = apply(expand.grid('par',1:nrow(paramsGpu), 'sim', 1:Nsim), 1, paste, collapse='')
```

```{r plotSimSetup, eval = F}
library(raster)
simRaster = brick(myRaster, 
  nl = ncol(simMat)*nrow(paramsGpu))
system.time(values(simRaster) <- as.vector(as.matrix(simMat)))
names(simRaster) = theNames
```

```{r plotSim, fig.height=5, fig.width=4, out.width="paste0(98/nrow(paramsGpu), '%')", fig.cap='simulations', fig.subcap = 'theNames', eval = F}
par(mar=rep(0.1, 4))
for(D in names(simRaster)) {
  plot(extent(simRaster))
  plot(simRaster[[D]], legend=FALSE, add=TRUE)
}
  
```



outputChol a = cbind(Y, 1), solve for a

# Backsolve

```{r backsolve, echo=TRUE, eval=F}
  
#solveMat = -99 +0*simMat
solveMat=vclMatrix(0, nrow(simMat),ncol(simMat),type=gpuR::typeof(outputChol))

gpuRandom:::backsolveBatchBackend(
  solveMat, outputChol, simMat, 
  diagIsOne = TRUE,   
  Nglobal = NglobalChol,
  Nlocal = NlocalChol,
  NlocalCache = NlocalCache)

NglobalChol
NlocalChol
NglobalChol/NlocalChol

as.matrix(simMat[1:12,])

as.matrix(solveMat[1:12,])

L = as.matrix(outputChol[1:ncol(outputChol), ])
L[!lower.tri(L, diag=TRUE)] = 0
diag(L) = 1
L[1:4,1:4]

solve(L, as.matrix(simMat[1:ncol(outputChol),]))[1:12, ]

```




```{r batchMaternSwussRaub, eval=FALSE}
data('swissRain', package='geostatsp')
sr2 = swissRain[1:4,]
sr2@coords = sr2@coords
dist(sr2@coords)
myParamsSR = geostatsp::fillParam(c(
  variance=2,nugget=1, anisoAngleRadians=0,
  range=12*1000, shape=1, anisoRatio = 1))

myParamsBatchSR1 = rbind(myParamsSR, myParamsSR)
myParamsBatchSR = cbind(myParamsBatchSR1, 
        matrix(0, nrow(myParamsBatchSR1), 22-ncol(myParamsBatchSR1)))

outputSwissRain = vclMatrix(0, 
        nrow(myParamsBatchSR)*length(sr2),length(sr2),type='double')
gpuRandom:::maternBatchBackend(
    var=outputSwissRain,
    coords=vclMatrix(sr2@coords, type='double'), 
    param=vclMatrix(myParamsBatchSR, type='double'),  
    Nglobal = c(1,1,1), 
    Nlocal = c(1,1,1))
geostatsp::matern(sr2, myParamsSR)
as.matrix(outputSwissRain)
```
# extra info

```{r gpuInfo, echo=TRUE}
gpuR::gpuInfo()
```





