<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Random uniform}
-->


`https://github.com/clMathLibraries/clRNG`



```{r date}
date()
```


```{r packages, results='hide'}
library('gpuR')
```

Use double precision if the GPU supports it
```{r setType}
theType = c('float','double')[1+gpuInfo()$double_support]
theType
#setContext(   grep('gpu', listContexts()$device_type) [2]    )
```


#new random normals
```{r rnorm}
Nglobal = c(64,4)
streams = gpuR::vclMatrix(gpuRandom::CreateStreams(prod(Nglobal)))

a<-gpuRandom::rnorm(c(200,200), streams=streams, workgroupSize=Nglobal, type="double")

#avector<-as.vector(as.matrix(a))
#hist(avector,breaks=40)
#gpuRandom::qqnorm(avector, workgroupSize = Nglobal)

```

#new random uniforms
```{r unif}
b<-gpuRandom::runif(c(200,800), workgroupSize=Nglobal, type="double")
#bvector<-as.vector(as.matrix(b))
#hist(bvector, breaks=40)
```


















Generate some uniforms
```{r test, eval=FALSE}
Nglobal = 4
streams = gpuRandom::CreateStreams(Nglobal);
t(streams)



x = vclVector(length=8L, type=theType)

streams2 <- gpuRandom::gpuRn(x, streams=streams,random_type = "uniform")
t(streams)[1:4,]
t(streams2)[1:4,]
as.vector(x)

#Generate some different uniforms

gpuRandom::gpuRn(x, streams=streams2,random_type = "uniform")
as.vector(x)


#Reuse the intial seed

y=vclVector(length=8L,type="double")
gpuRandom::gpuRn(y, streams=streams,random_type = "uniform")
as.vector(y)




Nglobal = c(64,4)
streams = gpuRandom::CreateStreams(prod(Nglobal))
if(gpuInfo()$maxAllocatableMem > 1e10) {
  NperItem = 1000
} else {
  NperItem = 100
}
x = vclVector(length=as.integer(prod(Nglobal)*NperItem), type=theType)
length(x)

system.time(junk <- runif(length(x)))
system.time(streams <- gpuRandom::gpuRn(x,  streams=streams,Nglobal, random_type = "uniform"))

xVec = as.vector(x)

hist(xVec, xlim=c(0,1),breaks=40)

xMat = matrix(xVec, ncol=prod(Nglobal), byrow=TRUE)

#theLim = 0.5 + 0.1*c(-1,1)
#plot(as.vector(xMat[-1,1]), as.vector(xMat[-nrow(xMat),1]), xlim = theLim, ylim=theLim, pch='.')
#plot(as.vector(xMat[-1,2]), as.vector(xMat[-nrow(xMat),2]), xlim = theLim, ylim=theLim, pch='.')



# Random normals
#Generate some random normals

Nglobal = c(64,4)
streams = gpuRandom::CreateStreams(prod(Nglobal))
x = vclVector(length=8L, type=theType)

gpuRandom::gpuRn(x, streams=streams, workgroupSize = Nglobal,
                                         localSize = c(2,2),
                                         random_type="normal")
as.vector(x)




#Compare run time for random normals


if(gpuInfo()$maxAllocatableMem > 1e10) {
  NperItem = 5e5}else {NperItem = 500}


z = vclVector(0, length=as.integer(prod(Nglobal)*NperItem), type="double")
length(z)

system.time(junk <- rnorm(length(z)))
system.time(streams <- gpuRandom::gpuRn(z, streams=streams, 
                                         workgroupSize = Nglobal,
                                         localSize = c(2,2),
                                         random_type="normal"))


#Plot histgram for random normals


zVec = as.vector(z)


hist(zVec,breaks=40)


#qqnorm(zVec)
```




