<!--
%\VignetteIndexEntry{Examples of an html document with subfigures}
%\VignetteEngine{Pmisc::plainKnit}
-->

```{r setup, include=FALSE}

# to compile

Pmisc::make('document.Rmd', suffix='html')


library('knitr')
library('Pmisc')

knitr::knit_hooks$set(
	marginsp = function(before, options, envir){	
		if(!before) return()
# use small margins
		par(mar=c(1.5+0.9*options$marginsp,
				1.5+0.9*options$marginsp,0.2,0.2),
				mgp=c(1.45, 0.45, 0),cex=1.25)
	}		
)

knitr::knit_hooks$set(plot=hook_plot_htmlsubfig)


knitr::opts_chunk$set(echo=FALSE, prompt=TRUE, comment=NA,
		dev='png', marginsp=1, fig.cap=' ',
		fig.width=4, fig.height=4, 
		tidy=TRUE,tidy.opts=list(indent=2, width.cutoff=55)
)


# if you'll be converting md to tex, can use the following
if(FALSE) {
	knitr::knit_hooks$set(plot=hook_plot_tex)
	knitr::opts_chunk$set(out.width='0.45\\textwidth', 
			dev='pdf', fig.align='center')
}




options(width=80)

bibFile = 'myDocBib.bib'
cat('
@article{lindgren2011explicit,
  title={An explicit link between Gaussian fields and Gaussian Markov random fields the stochastic partial differential equation approach},
  author={Lindgren, Finn and Rue, Haavard and Lindstrom, Johan},
  journal={Journal of the Royal Statistical Society B},
  volume={73},
  number={4},
  pages={423-498},
  year={2011},
  publisher={Wiley}
}
', file=bibFile, encoding='UTF8')

```
		
```{r theHeader, echo=FALSE}
Pmisc::markdownHeader(
	title="Pmisc html subfigures", 		
	author='Patrick Brown',
	slides=FALSE,
	bibliography = bibFile,
	csl = NULL,#system.file('src','chicago-author-date.csl', package='Pmisc'),
	css = system.file('src','article.css', package='Pmisc'),
	headerincludes = c(
		'\\usepackage{subcaption}',
		'\\newcommand{\\subfloat}[2][need a sub-caption]{\\subcaptionbox{#1}{#2} }'
	)
)
```


# Introduction


@lindgren2011explicit is a very good paper.



```{r aplot, fig.ncol=2, fig.cap='Uninteresting plots', fig.subcap=c('a','b','c','d')}
plot(1:10)

plot(1:10+2)


plot(1:10-4)


plot(1:10+4)
```


# References

