<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{INLA examples}
-->

```{r inlaWorkaround, include=FALSE}
# use the static INLA on linux machines
# to avoid possible 'libgomp not found' errors
if(Sys.info()['sysname'] =='Linux' &
  requireNamespace("INLA")) {   
  INLA::inla.setOption(inla.call = 
      system.file(paste(
          "bin/linux/",          
          ifelse(
            .Machine$sizeof.pointer == 4, 
            "32", "64"),
          'bit/inla.static', sep=''),
        package="INLA")) 
}
```


# Weibull With Cure Fraction

the data
```{r kidneyData, eval = requireNamespace("INLA"), purl= requireNamespace("INLA")}
data(Kidney, package='INLA')
head(Kidney)
```

scale the response variable
```{r scale, eval = requireNamespace("INLA"), purl= requireNamespace("INLA")}
Kidney$years = Kidney$time / 365.25
```




run the model 

```{r fitInla, eval = requireNamespace("INLA"), purl= requireNamespace("INLA")}
library("INLA")
mod = inla(
  inla.surv(years, event) ~ age * sex + 
    f(ID, model="iid", prior='pc.prec', param=c(0.5, 0.1)), 
  family="weibullcure", 
  control.family = list(hyper=list(
      'log alpha' = list(
        prior='loggamma', param=c(1,1)),
      'logit probability' = list(
        prior='logitbeta', param=c(1,1))
    )),
  data=Kidney, 
  control.inla=list(h=0.001, int.strategy='grid'), 
  control.compute = list(config=TRUE),
  control.mode = list(theta=c(0,-5,4), restart=TRUE),
  verbose=TRUE)
```

results

```{r results, eval = requireNamespace("INLA"), purl= requireNamespace("INLA")}
knitr::kable(mod$summary.fixed, digits=3)
knitr::kable(mod$summary.hyper, digits=3)
```

standard deviation
```{r sdSummary, eval = requireNamespace("INLA"), purl= requireNamespace("INLA")}
modSd = Pmisc::priorPost(mod)
knitr::kable(modSd$summary, digits=3)
```

```{r sdPlot, eval = requireNamespace("INLA"), purl= requireNamespace("INLA")}
for(D in grep('^sd', names(modSd), value=TRUE)) {
  do.call(matplot, modSd[[D]]$matplot)
  do.call(legend, modSd$legend)
}
```

```{r alphaPlot, eval = requireNamespace("INLA"), purl= requireNamespace("INLA")}
do.call(matplot, modSd$alpha$matplot)
do.call(legend, modSd$legend)
```

```{r probPlot, eval = requireNamespace("INLA"), purl= requireNamespace("INLA")}
do.call(matplot, modSd$prob$matplot)
do.call(legend, modSd$legend)
```

```{r sampleDensHaz}
xSeq = seq(0,1/12,len=1000)
myDens = Pmisc::sampleDensHaz(mod, xSeq, n=25)
matplot(xSeq*365.25, myDens[,'dens',]/365.25, type='l',
  col = '#00000020', lty=1, xlab='days', ylab='dens')
```

# Gamma

```{r gammaData}
data('meuse', package='sp')
distBreaks = seq(0, 1, len=101)
meuse$distCut = cut(meuse$dist, breaks=distBreaks, 
  right=FALSE)
meuse$soilFac = factor(meuse$soil, levels=1:3, 
  labels=c('Calcerous','Non-Calcerous','Red Brick'))
meuse[1:4,c('cadmium','elev','dist','distCut', 'soilFac')]
```


```{r gammaFit, eval = requireNamespace("INLA"), purl= requireNamespace("INLA")}
library("INLA", quietly=TRUE)
mod = inla(
  cadmium ~ elev + soilFac + 
  f(distCut, model='rw2', 
    prior = 'pc.prec', param = c(0.01, 0.5),
    values = levels(distCut), constr=FALSE,
    extraconstr = list(
      A = model.matrix(~0+cut(0.25, distBreaks)), e=0
      )),
  data = meuse, family = 'gamma',
  control.family = list(hyper=list(
    prec=list(prior = 'pc.prec', param = c(0.1, 0.5)))),
  verbose=TRUE
  )
```

```{r results, eval = exists("mod")}
```

standard deviation
```{r sdSummary, eval = exists("mod")}
```


```{r sdPlot, eval = exists("mod")}
```

```{r distPlot, eval = exists("mod")}
mod$summary.random$distCut[is.na(mod$summary.random$distCut$mean),-1] = 0
matplot(distBreaks[-length(distBreaks)], 
  exp(mod$summary.random$distCut[,paste0(c('0.5','0.025','0.975'), 'quant')]),
  ylab = 'relative rate', xlab='distance', type='l', lty=c(1,2,2),
  col='black', log='y')
legend("bottomleft", lty=c(1,2), legend=c('median','95% CI'), bty='n')
```
