# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_fisher_sim_gpu <- function(srR, scR, ansR, streamsR, max_global_size) {
    .Call('_clRNG_cpp_fisher_sim_gpu', PACKAGE = 'clRNG', srR, scR, ansR, streamsR, max_global_size)
}

cpp_mrg31k3pCreateStreams <- function(numWorkItems) {
    .Call('_clRNG_cpp_mrg31k3pCreateStreams', PACKAGE = 'clRNG', numWorkItems)
}

cpp_random_numberGpu <- function(xR, streamsR, max_global_size, max_local_size, random_type, precision_type) {
    .Call('_clRNG_cpp_random_numberGpu', PACKAGE = 'clRNG', xR, streamsR, max_global_size, max_local_size, random_type, precision_type)
}

