# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_mrg31k3pCreateStreams <- function(numWorkItems) {
    .Call('_clRNG_cpp_mrg31k3pCreateStreams', PACKAGE = 'clRNG', numWorkItems)
}

cpp_runifGpu <- function(xR, streamsR, max_global_size, max_local_size, type) {
    .Call('_clRNG_cpp_runifGpu', PACKAGE = 'clRNG', xR, streamsR, max_global_size, max_local_size, type)
}

