# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Initiate a single context
#' @description Initiate a viennaCL context on the supplied platform and device
#' @return An integer value representing the context id
#' @export
initSingleContext <- function(platformId, deviceId, contextId) {
    .Call(`_gpuRbarebones_initSingleContext`, platformId, deviceId, contextId)
}

#' @title Info for an OpenCL Context
#' @description Provide information on a specified context
#' @return data frame with one row and elements
#' @return \item{context}{Integer identifying context}
#' @return \item{platform}{Character string listing OpenCL platform}
#' @return \item{platform_index}{Integer identifying platform}
#' @return \item{device}{Character string listing device name}
#' @return \item{device_index}{Integer identifying device}
#' @return \item{device_type}{Character string labeling device (e.g. gpu)}
#' @export
contextInfo <- function(contextId) {
    .Call(`_gpuRbarebones_contextInfo`, contextId)
}

#' @title Current Device Information
#' @description Check current device information
#' @return list containing
#' @return \item{device}{Character string of device name}
#' @return \item{device_index}{Integer identifying device}
#' @return \item{device_type}{Character string identifying device type (e.g. gpu)}
#' @export
currentDevice <- function() {
    .Call(`_gpuRbarebones_currentDevice`)
}

#' @title Detect Number of Platforms
#' @description Find out how many OpenCL enabled platforms are available.
#' @return An integer value representing the number of platforms available.
#' @details see https://laanwj.github.io/2016/05/06/opencl-ubuntu1604.html
#' @seealso \link{detectGPUs}
#' @export
detectPlatforms2 <- function() {
    .Call(`_gpuRbarebones_detectPlatforms2`)
}

#' @title Details of platforms
#' @description Details of OpenCL enabled platforms which are available.
#' @return A list
#' @seealso \link{detectGPUs}
#' @export
platformsAvailable <- function() {
    .Call(`_gpuRbarebones_platformsAvailable`)
}

