# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initContexts <- function() {
    invisible(.Call('_gpuRbarebones_initContexts', PACKAGE = 'gpuRbarebones'))
}

#' @title Available OpenCL Contexts
#' @description Provide a data.frame of available OpenCL contexts and
#' associated information.
#' @return data.frame containing the following fields
#' @return \item{context}{Integer identifying context}
#' @return \item{platform}{Character string listing OpenCL platform}
#' @return \item{platform_index}{Integer identifying platform}
#' @return \item{device}{Character string listing device name}
#' @return \item{device_index}{Integer identifying device}
#' @return \item{device_type}{Character string labeling device (e.g. gpu)}
#' @export
listContexts <- function() {
    .Call('_gpuRbarebones_listContexts', PACKAGE = 'gpuRbarebones')
}

#' @title Current Context
#' @description Get current context index
#' @return An integer reflecting the context listed in \link{listContexts}
#' @export
currentContext <- function() {
    .Call('_gpuRbarebones_currentContext', PACKAGE = 'gpuRbarebones')
}

cpp_setContext <- function(id) {
    invisible(.Call('_gpuRbarebones_cpp_setContext', PACKAGE = 'gpuRbarebones', id))
}

getContextPtr <- function(ctx_id) {
    .Call('_gpuRbarebones_getContextPtr', PACKAGE = 'gpuRbarebones', ctx_id)
}

cpp_deviceType <- function(gpu_idx_, ctx_idx) {
    .Call('_gpuRbarebones_cpp_deviceType', PACKAGE = 'gpuRbarebones', gpu_idx_, ctx_idx)
}

cpp_detectGPUs <- function(platform_idx) {
    .Call('_gpuRbarebones_cpp_detectGPUs', PACKAGE = 'gpuRbarebones', platform_idx)
}

cpp_gpuInfo <- function(gpu_idx_, ctx_idx) {
    .Call('_gpuRbarebones_cpp_gpuInfo', PACKAGE = 'gpuRbarebones', gpu_idx_, ctx_idx)
}

cpp_cpuInfo <- function(cpu_idx_, ctx_idx) {
    .Call('_gpuRbarebones_cpp_cpuInfo', PACKAGE = 'gpuRbarebones', cpu_idx_, ctx_idx)
}

#' @title Current Device Information
#' @description Check current device information
#' @return list containing
#' @return \item{device}{Character string of device name}
#' @return \item{device_index}{Integer identifying device}
#' @return \item{device_type}{Character string identifying device type (e.g. gpu)}
#' @export
currentDevice <- function() {
    .Call('_gpuRbarebones_currentDevice', PACKAGE = 'gpuRbarebones')
}

cpp_detectCPUs <- function(platform_idx) {
    .Call('_gpuRbarebones_cpp_detectCPUs', PACKAGE = 'gpuRbarebones', platform_idx)
}

preferred_wg_size <- function(sourceCode_, kernel_name, ctx_id) {
    .Call('_gpuRbarebones_preferred_wg_size', PACKAGE = 'gpuRbarebones', sourceCode_, kernel_name, ctx_id)
}

#' @title Detect Number of Platforms
#' @description Find out how many OpenCL enabled platforms are available.
#' @return An integer value representing the number of platforms available.
#' @seealso \link{detectGPUs}
#' @export
detectPlatforms2 <- function() {
    .Call('_gpuRbarebones_detectPlatforms2', PACKAGE = 'gpuRbarebones')
}

#' @title Detect Number of Platforms
#' @description Find out how many OpenCL enabled platforms are available.
#' @return An integer value representing the number of platforms available.
#' @seealso \link{detectGPUs}
#' @export
detectPlatforms <- function() {
    .Call('_gpuRbarebones_detectPlatforms', PACKAGE = 'gpuRbarebones')
}

#' @title Return Current Platform
#' @description Find out which platform is currently in use
#' @return \item{platform}{Name of the current platform}
#' @return \item{platform_index}{Index of current platform}
#' @seealso \link{detectPlatforms}
#' @export
currentPlatform <- function() {
    .Call('_gpuRbarebones_currentPlatform', PACKAGE = 'gpuRbarebones')
}

cpp_platformInfo <- function(platform_idx_) {
    .Call('_gpuRbarebones_cpp_platformInfo', PACKAGE = 'gpuRbarebones', platform_idx_)
}

#' @title Details of platforms
#' @description Details of OpenCL enabled platforms which are available.
#' @return A list
#' @seealso \link{detectGPUs}
#' @export
platformsAvailable <- function() {
    .Call('_gpuRbarebones_platformsAvailable', PACKAGE = 'gpuRbarebones')
}

#' @title Synchronize Device Execution
#' @description This pauses execution until the processing is complete
#' on the device (CPU/GPU/etc.).  This is important especially for
#' benchmarking applications.
#' @return NULL
#' @author Charles Determan Jr.
#' @examples \dontrun{
#'     mat <- vclMatrix(rnorm(500^2), ncol = 500, nrow = 500)
#'     system.time(mat %*% mat)
#'     system.time(mat %*% mat; synchronize())
#' }
#' @export
synchronize <- function() {
    invisible(.Call('_gpuRbarebones_synchronize', PACKAGE = 'gpuRbarebones'))
}

cpp_vcl_nrow <- function(ptrA, type_flag) {
    .Call('_gpuRbarebones_cpp_vcl_nrow', PACKAGE = 'gpuRbarebones', ptrA, type_flag)
}

cpp_vcl_ncol <- function(ptrA, type_flag) {
    .Call('_gpuRbarebones_cpp_vcl_ncol', PACKAGE = 'gpuRbarebones', ptrA, type_flag)
}

cpp_vclVector_size <- function(ptrA, type_flag) {
    .Call('_gpuRbarebones_cpp_vclVector_size', PACKAGE = 'gpuRbarebones', ptrA, type_flag)
}

