// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// cpp_cholGpu
SEXP cpp_cholGpu(SEXP xR, SEXP DR, int max_local_size, const int ctx_id, const char kernel);
RcppExport SEXP _geostatsgpu_cpp_cholGpu(SEXP xRSEXP, SEXP DRSEXP, SEXP max_local_sizeSEXP, SEXP ctx_idSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xR(xRSEXP);
    Rcpp::traits::input_parameter< SEXP >::type DR(DRSEXP);
    Rcpp::traits::input_parameter< int >::type max_local_size(max_local_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type ctx_id(ctx_idSEXP);
    Rcpp::traits::input_parameter< const char >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cholGpu(xR, DR, max_local_size, ctx_id, kernel));
    return rcpp_result_gen;
END_RCPP
}
// cpp_maternGpu
SEXP cpp_maternGpu(SEXP varR, SEXP DofLDLR, SEXP XYR, SEXP crossprodR, SEXP coordsR, SEXP paramR, const int type, const int upper, int max_local_size, const int ctx_id);
RcppExport SEXP _geostatsgpu_cpp_maternGpu(SEXP varRSEXP, SEXP DofLDLRSEXP, SEXP XYRSEXP, SEXP crossprodRSEXP, SEXP coordsRSEXP, SEXP paramRSEXP, SEXP typeSEXP, SEXP upperSEXP, SEXP max_local_sizeSEXP, SEXP ctx_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type varR(varRSEXP);
    Rcpp::traits::input_parameter< SEXP >::type DofLDLR(DofLDLRSEXP);
    Rcpp::traits::input_parameter< SEXP >::type XYR(XYRSEXP);
    Rcpp::traits::input_parameter< SEXP >::type crossprodR(crossprodRSEXP);
    Rcpp::traits::input_parameter< SEXP >::type coordsR(coordsRSEXP);
    Rcpp::traits::input_parameter< SEXP >::type paramR(paramRSEXP);
    Rcpp::traits::input_parameter< const int >::type type(typeSEXP);
    Rcpp::traits::input_parameter< const int >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< int >::type max_local_size(max_local_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type ctx_id(ctx_idSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_maternGpu(varR, DofLDLR, XYR, crossprodR, coordsR, paramR, type, upper, max_local_size, ctx_id));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_geostatsgpu_cpp_cholGpu", (DL_FUNC) &_geostatsgpu_cpp_cholGpu, 5},
    {"_geostatsgpu_cpp_maternGpu", (DL_FUNC) &_geostatsgpu_cpp_maternGpu, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_geostatsgpu(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
