# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply lower triangular matrix
#' 
#' Multiplies a lower triangular matrix by a rectangular matrix
#'
#' @param C output matrix
#' @param A lower triangular matrix
#' @param B rectangular matrix
#' @param Nglobal0 number of global work items
#' @param Nlocal0 number of local work items
#' @param NlocalCache rows of B to cache in local memory
#' @export
multiplyLower <- function(C, A, B, Nglobal0, Nlocal0, NlocalCache, type) {
    .Call('_gpuMatrix_multiplyLower', PACKAGE = 'gpuMatrix', C, A, B, Nglobal0, Nlocal0, NlocalCache, type)
}

