// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_mrg31k3pCreateStreams
Rcpp::IntegerMatrix cpp_mrg31k3pCreateStreams(int numWorkItems);
RcppExport SEXP _clRNG_cpp_mrg31k3pCreateStreams(SEXP numWorkItemsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type numWorkItems(numWorkItemsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_mrg31k3pCreateStreams(numWorkItems));
    return rcpp_result_gen;
END_RCPP
}
// cpp_runifGpu
SEXP cpp_runifGpu(Rcpp::S4 xR, Rcpp::S4 yR, Rcpp::IntegerMatrix streamsR, int max_global_size, int max_local_size, std::string type);
RcppExport SEXP _clRNG_cpp_runifGpu(SEXP xRSEXP, SEXP yRSEXP, SEXP streamsRSEXP, SEXP max_global_sizeSEXP, SEXP max_local_sizeSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type xR(xRSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type yR(yRSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type streamsR(streamsRSEXP);
    Rcpp::traits::input_parameter< int >::type max_global_size(max_global_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_local_size(max_local_sizeSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_runifGpu(xR, yR, streamsR, max_global_size, max_local_size, type));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_clRNG_cpp_mrg31k3pCreateStreams", (DL_FUNC) &_clRNG_cpp_mrg31k3pCreateStreams, 1},
    {"_clRNG_cpp_runifGpu", (DL_FUNC) &_clRNG_cpp_runifGpu, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_clRNG(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
