// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// initSingleContext
SEXP initSingleContext(int platformId, int deviceId, int contextId);
RcppExport SEXP _gpuRbarebones_initSingleContext(SEXP platformIdSEXP, SEXP deviceIdSEXP, SEXP contextIdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type platformId(platformIdSEXP);
    Rcpp::traits::input_parameter< int >::type deviceId(deviceIdSEXP);
    Rcpp::traits::input_parameter< int >::type contextId(contextIdSEXP);
    rcpp_result_gen = Rcpp::wrap(initSingleContext(platformId, deviceId, contextId));
    return rcpp_result_gen;
END_RCPP
}
// contextInfo
DataFrame contextInfo(int contextId);
RcppExport SEXP _gpuRbarebones_contextInfo(SEXP contextIdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type contextId(contextIdSEXP);
    rcpp_result_gen = Rcpp::wrap(contextInfo(contextId));
    return rcpp_result_gen;
END_RCPP
}
// currentDevice
SEXP currentDevice();
RcppExport SEXP _gpuRbarebones_currentDevice() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(currentDevice());
    return rcpp_result_gen;
END_RCPP
}
// detectPlatforms2
int detectPlatforms2();
RcppExport SEXP _gpuRbarebones_detectPlatforms2() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(detectPlatforms2());
    return rcpp_result_gen;
END_RCPP
}
// platformsAvailable
List platformsAvailable();
RcppExport SEXP _gpuRbarebones_platformsAvailable() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(platformsAvailable());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gpuRbarebones_initSingleContext", (DL_FUNC) &_gpuRbarebones_initSingleContext, 3},
    {"_gpuRbarebones_contextInfo", (DL_FUNC) &_gpuRbarebones_contextInfo, 1},
    {"_gpuRbarebones_currentDevice", (DL_FUNC) &_gpuRbarebones_currentDevice, 0},
    {"_gpuRbarebones_detectPlatforms2", (DL_FUNC) &_gpuRbarebones_detectPlatforms2, 0},
    {"_gpuRbarebones_platformsAvailable", (DL_FUNC) &_gpuRbarebones_platformsAvailable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_gpuRbarebones(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
